-- Durable team unit-TOI aggregate for contextual team-style rankings.
--
-- `unit_toi_seconds` and `team_unit_pool_toi_seconds` intentionally use
-- pooled player-seconds. For example, a 10-second 5v5 forward trio segment
-- contributes 30 pooled player-seconds. This keeps forward line, defense pair,
-- and PP unit shares on a consistent denominator and avoids presenting summed
-- player PPTOI as literal clock time.

create table if not exists public.team_unit_toi (
  id bigint generated by default as identity primary key,
  season_id integer not null,
  snapshot_date date not null,
  game_id integer not null,
  game_date date null,
  team_id integer not null,
  team_abbrev text null,
  unit_type text not null,
  unit_number integer not null,
  player_ids integer[] not null default '{}'::integer[],
  player_count integer not null default 0,
  unit_toi_seconds double precision not null,
  team_unit_pool_toi_seconds double precision not null,
  unit_share double precision generated always as (
    case
      when team_unit_pool_toi_seconds > 0
        then unit_toi_seconds / team_unit_pool_toi_seconds
      else null
    end
  ) stored,
  toi_basis text not null default 'pooled_player_seconds',
  source_table text not null,
  source_version text not null default 'team_unit_toi_v1',
  coverage_status text not null default 'complete',
  coverage_warnings jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_unit_toi_unit_type_check
    check (unit_type in ('forward_line', 'defense_pair', 'power_play')),
  constraint team_unit_toi_unit_number_check
    check (unit_number > 0),
  constraint team_unit_toi_seconds_check
    check (unit_toi_seconds >= 0 and team_unit_pool_toi_seconds >= 0),
  constraint team_unit_toi_basis_check
    check (toi_basis in ('pooled_player_seconds')),
  constraint team_unit_toi_source_table_check
    check (source_table in ('nhl_api_shift_rows', 'powerPlayCombinations')),
  constraint team_unit_toi_coverage_status_check
    check (coverage_status in ('complete', 'partial', 'source_gap')),
  constraint team_unit_toi_unique_context
    unique (season_id, snapshot_date, game_id, team_id, unit_type, unit_number)
);

create index if not exists idx_team_unit_toi_latest
  on public.team_unit_toi (
    season_id,
    snapshot_date desc,
    unit_type,
    team_id,
    unit_number
  );

create index if not exists idx_team_unit_toi_game_team
  on public.team_unit_toi (season_id, game_id, team_id, unit_type);

create index if not exists idx_team_unit_toi_share
  on public.team_unit_toi (
    season_id,
    snapshot_date,
    unit_type,
    unit_share desc
  );

comment on table public.team_unit_toi is
  'Durable team/game unit-usage aggregate for contextual rankings. Stores forward-line, defense-pair, and PP-unit pooled player-second shares.';

comment on column public.team_unit_toi.unit_toi_seconds is
  'Unit pooled player-seconds, not raw clock seconds.';

comment on column public.team_unit_toi.team_unit_pool_toi_seconds is
  'Team denominator pooled player-seconds for the same unit type and game.';

comment on column public.team_unit_toi.unit_share is
  'Generated unit_toi_seconds / team_unit_pool_toi_seconds share.';

alter table public.team_unit_toi enable row level security;

revoke insert, update, delete, truncate, references, trigger
  on table public.team_unit_toi
  from anon, authenticated;

grant select on table public.team_unit_toi to anon, authenticated;

drop policy if exists "public_read" on public.team_unit_toi;
create policy "public_read"
  on public.team_unit_toi
  for select
  to anon, authenticated
  using (true);
