import { describe, expect, it } from "vitest";

import type { NhlShotFeatureRow } from "../supabase/Upserts/nhlShotFeatureBuilder";
import { buildDeploymentContextForShot, buildShiftStintsByGameId } from "./deploymentContext";

function createShotRow(
  overrides: Partial<NhlShotFeatureRow> = {}
): NhlShotFeatureRow {
  return {
    featureVersion: 1,
    gameId: 2025021001,
    seasonId: 20252026,
    gameDate: "2026-01-01",
    eventId: 100,
    eventIndex: 1,
    sortOrder: 1,
    periodNumber: 1,
    periodType: "REG",
    gameSecondsElapsed: 300,
    periodSecondsElapsed: 300,
    eventOwnerTeamId: 10,
    eventOwnerSide: "home",
    strengthState: "EV",
    strengthExact: "5v5",
    shotEventType: "shot-on-goal",
    isGoal: false,
    isOwnGoal: false,
    isShotOnGoal: true,
    isMissedShot: false,
    isBlockedShot: false,
    isUnblockedShotAttempt: true,
    shooterPlayerId: 91,
    shootingPlayerId: 91,
    scoringPlayerId: null,
    goalieInNetId: 31,
    shotType: "wrist",
    zoneCode: "O",
    rawX: 75,
    rawY: 10,
    normalizedX: 75,
    normalizedY: 10,
    shotDistanceFeet: 18,
    shotAngleDegrees: 30,
    shooterRosterPosition: null,
    shooterPositionGroup: null,
    isDefensemanShooter: null,
    shooterHandedness: null,
    goalieCatchHand: null,
    shooterGoalieHandednessMatchup: null,
    previousEventId: null,
    previousEventTypeDescKey: null,
    previousEventTeamId: null,
    previousEventSameTeam: null,
    timeSincePreviousEventSeconds: null,
    distanceFromPreviousEvent: null,
    homeScoreBeforeEvent: null,
    awayScoreBeforeEvent: null,
    homeScoreDiffBeforeEvent: null,
    awayScoreDiffBeforeEvent: null,
    ownerScoreDiffBeforeEvent: null,
    ownerScoreDiffBucket: null,
    scoreEffectsGameTimeSegment: null,
    ownerScoreDiffByGameTimeBucket: null,
    isLateGameClose: null,
    isLateGameTrailing: null,
    isLateGameLeading: null,
    isFinalFiveMinutes: null,
    isFinalTwoMinutes: null,
    possessionSequenceId: null,
    possessionEventCount: null,
    possessionDurationSeconds: null,
    possessionStartEventId: null,
    possessionStartTypeDescKey: null,
    possessionStartZoneCode: null,
    possessionRegainedFromOpponent: null,
    possessionRegainEventTypeDescKey: null,
    possessionEnteredOffensiveZone: null,
    isReboundShot: false,
    reboundSourceEventId: null,
    reboundSourceTypeDescKey: null,
    reboundTimeDeltaSeconds: null,
    reboundDistanceFromSource: null,
    reboundLateralDisplacementFeet: null,
    reboundDistanceDeltaFeet: null,
    reboundAngleChangeDegrees: null,
    createsRebound: false,
    isRushShot: false,
    rushSourceEventId: null,
    rushSourceTypeDescKey: null,
    rushTimeSinceSourceSeconds: null,
    rushSourceTeamRelativeZoneCode: null,
    isFlurryShot: false,
    flurrySequenceId: null,
    flurryShotIndex: null,
    flurryShotCount: null,
    flurrySequenceStartEventId: null,
    flurrySequenceEndEventId: null,
    missReasonRaw: null,
    missReasonBucket: null,
    isShortSideMiss: false,
    ownerPowerPlayAgeSeconds: null,
    opponentPowerPlayAgeSeconds: null,
    shooterShiftAgeSeconds: null,
    shooterPreviousShiftGapSeconds: null,
    shooterPreviousShiftDurationSeconds: null,
    ownerAverageShiftAgeSeconds: null,
    ownerMaxShiftAgeSeconds: null,
    ownerAveragePreviousShiftGapSeconds: null,
    ownerAveragePreviousShiftDurationSeconds: null,
    opponentAverageShiftAgeSeconds: null,
    opponentMaxShiftAgeSeconds: null,
    opponentAveragePreviousShiftGapSeconds: null,
    opponentAveragePreviousShiftDurationSeconds: null,
    eastWestMovementFeet: null,
    northSouthMovementFeet: null,
    crossedRoyalRoad: null,
    ownerForwardCountOnIce: null,
    ownerDefenseCountOnIce: null,
    opponentForwardCountOnIce: null,
    opponentDefenseCountOnIce: null,
    ownerGoalieOnIce: null,
    opponentGoalieOnIce: null,
    ownerSkaterDeploymentBucket: null,
    opponentSkaterDeploymentBucket: null,
    skaterRoleMatchupBucket: null,
    isPenaltyShotEvent: false,
    isShootoutEvent: false,
    isDelayedPenaltyEvent: false,
    isEmptyNetEvent: false,
    isOvertimeEvent: false,
    hasRareManpower: false,
    ...overrides,
  };
}

describe("deploymentContext", () => {
  it("builds deployment counts and buckets from on-ice stints", () => {
    const stintsByGameId = buildShiftStintsByGameId([
      { game_id: 2025021001, shift_id: 1, team_id: 10, player_id: 91, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 2, team_id: 10, player_id: 92, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 3, team_id: 10, player_id: 93, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 4, team_id: 10, player_id: 94, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 5, team_id: 10, player_id: 95, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 6, team_id: 10, player_id: 31, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 7, team_id: 20, player_id: 81, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 8, team_id: 20, player_id: 82, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 9, team_id: 20, player_id: 83, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 10, team_id: 20, player_id: 84, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 11, team_id: 20, player_id: 85, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
      { game_id: 2025021001, shift_id: 12, team_id: 20, player_id: 41, period: 1, start_seconds: 0, end_seconds: 600, duration_seconds: 600, season_id: 20252026, game_date: "2026-01-01", shift_number: 1 },
    ] as never[]);

    const context = buildDeploymentContextForShot(
      createShotRow(),
      stintsByGameId.get(2025021001) ?? [],
      new Map([
        [91, "L"],
        [92, "C"],
        [93, "R"],
        [94, "D"],
        [95, "D"],
        [31, "G"],
        [81, "L"],
        [82, "C"],
        [83, "R"],
        [84, "R"],
        [85, "D"],
        [41, "G"],
      ])
    );

    expect(context).toEqual({
      ownerForwardCountOnIce: 3,
      ownerDefenseCountOnIce: 2,
      opponentForwardCountOnIce: 4,
      opponentDefenseCountOnIce: 1,
      ownerGoalieOnIce: true,
      opponentGoalieOnIce: true,
      ownerSkaterDeploymentBucket: "3F-2D",
      opponentSkaterDeploymentBucket: "4F-1D",
      skaterRoleMatchupBucket: "3F-2D_vs_4F-1D",
    });
  });

  it("returns null deployment context when no matching stint is present", () => {
    const context = buildDeploymentContextForShot(
      createShotRow(),
      [],
      new Map()
    );

    expect(context).toEqual({
      ownerForwardCountOnIce: null,
      ownerDefenseCountOnIce: null,
      opponentForwardCountOnIce: null,
      opponentDefenseCountOnIce: null,
      ownerGoalieOnIce: null,
      opponentGoalieOnIce: null,
      ownerSkaterDeploymentBucket: null,
      opponentSkaterDeploymentBucket: null,
      skaterRoleMatchupBucket: null,
    });
  });
});
