import { describe, expect, it } from "vitest";

import type { NhlShotFeatureRow } from "../supabase/Upserts/nhlShotFeatureBuilder";
import { enrichShotRowsWithTrainingContextMaps } from "./shotFeatureEnrichment";

function makeShotRow(
  overrides: Partial<NhlShotFeatureRow> = {}
): NhlShotFeatureRow {
  return {
    featureVersion: 1,
    gameId: 2025020001,
    seasonId: 20252026,
    gameDate: "2025-10-07",
    eventId: 101,
    eventIndex: 1,
    sortOrder: 101,
    periodNumber: 1,
    periodType: "REG",
    gameSecondsElapsed: 300,
    periodSecondsElapsed: 300,
    eventOwnerTeamId: 10,
    eventOwnerSide: "home",
    strengthState: "5v5",
    strengthExact: "5v5",
    shotEventType: "shot-on-goal",
    isGoal: false,
    isOwnGoal: false,
    isShotOnGoal: true,
    isMissedShot: false,
    isBlockedShot: false,
    isUnblockedShotAttempt: true,
    shooterPlayerId: 91,
    shootingPlayerId: 91,
    scoringPlayerId: null,
    goalieInNetId: 31,
    shotType: "wrist",
    zoneCode: "O",
    rawX: 70,
    rawY: 8,
    normalizedX: 70,
    normalizedY: 8,
    shotDistanceFeet: 20.62,
    shotAngleDegrees: 22.83,
    shooterRosterPosition: null,
    shooterPositionGroup: null,
    isDefensemanShooter: null,
    shooterHandedness: null,
    goalieCatchHand: null,
    shooterGoalieHandednessMatchup: null,
    previousEventId: null,
    previousEventTypeDescKey: null,
    previousEventTeamId: null,
    previousEventSameTeam: null,
    timeSincePreviousEventSeconds: null,
    distanceFromPreviousEvent: null,
    homeScoreBeforeEvent: 0,
    awayScoreBeforeEvent: 0,
    homeScoreDiffBeforeEvent: 0,
    awayScoreDiffBeforeEvent: 0,
    ownerScoreDiffBeforeEvent: 0,
    ownerScoreDiffBucket: "tied",
    scoreEffectsGameTimeSegment: "early",
    ownerScoreDiffByGameTimeBucket: "tied_early",
    isLateGameClose: false,
    isLateGameTrailing: false,
    isLateGameLeading: false,
    isFinalFiveMinutes: false,
    isFinalTwoMinutes: false,
    possessionSequenceId: null,
    possessionEventCount: null,
    possessionDurationSeconds: null,
    possessionStartEventId: null,
    possessionStartTypeDescKey: null,
    possessionStartZoneCode: null,
    possessionRegainedFromOpponent: null,
    possessionRegainEventTypeDescKey: null,
    possessionEnteredOffensiveZone: null,
    isReboundShot: false,
    reboundSourceEventId: null,
    reboundSourceTypeDescKey: null,
    reboundTimeDeltaSeconds: null,
    reboundDistanceFromSource: null,
    reboundLateralDisplacementFeet: null,
    reboundDistanceDeltaFeet: null,
    reboundAngleChangeDegrees: null,
    createsRebound: false,
    reboundControlOutcome: null,
    createsSecondChanceAllowed: false,
    createsGoalieFreeze: false,
    createsCoveredPuck: false,
    createsNoDangerContinuation: false,
    reboundOutcomeConfidence: null,
    isRushShot: false,
    rushSourceEventId: null,
    rushSourceTypeDescKey: null,
    rushTimeSinceSourceSeconds: null,
    rushSourceTeamRelativeZoneCode: null,
    isFlurryShot: false,
    flurrySequenceId: null,
    flurryShotIndex: null,
    flurryShotCount: null,
    flurrySequenceStartEventId: null,
    flurrySequenceEndEventId: null,
    missReasonRaw: null,
    missReasonBucket: null,
    isShortSideMiss: false,
    ownerPowerPlayAgeSeconds: null,
    opponentPowerPlayAgeSeconds: null,
    shooterShiftAgeSeconds: null,
    shooterPreviousShiftGapSeconds: null,
    shooterPreviousShiftDurationSeconds: null,
    ownerAverageShiftAgeSeconds: null,
    ownerMaxShiftAgeSeconds: null,
    ownerAveragePreviousShiftGapSeconds: null,
    ownerAveragePreviousShiftDurationSeconds: null,
    opponentAverageShiftAgeSeconds: null,
    opponentMaxShiftAgeSeconds: null,
    opponentAveragePreviousShiftGapSeconds: null,
    opponentAveragePreviousShiftDurationSeconds: null,
    ownerForwardCountOnIce: null,
    ownerDefenseCountOnIce: null,
    opponentForwardCountOnIce: null,
    opponentDefenseCountOnIce: null,
    ownerGoalieOnIce: null,
    opponentGoalieOnIce: null,
    ownerSkaterDeploymentBucket: null,
    opponentSkaterDeploymentBucket: null,
    skaterRoleMatchupBucket: null,
    eastWestMovementFeet: null,
    northSouthMovementFeet: null,
    crossedRoyalRoad: null,
    isPenaltyShotEvent: false,
    isShootoutEvent: false,
    isDelayedPenaltyEvent: false,
    isEmptyNetEvent: false,
    isOvertimeEvent: false,
    hasRareManpower: false,
    ...overrides,
  };
}

describe("shotFeatureEnrichment", () => {
  it("persists handedness, roster position, and deployment context onto shot rows", () => {
    const rows = enrichShotRowsWithTrainingContextMaps(
      [makeShotRow()],
      [
        {
          game_id: 2025020001,
          shift_id: 1,
          season_id: 20252026,
          game_date: "2025-10-07",
          player_id: 91,
          team_id: 10,
          period: 1,
          shift_number: 1,
          start_seconds: 250,
          end_seconds: 350,
          duration_seconds: 100,
        },
        {
          game_id: 2025020001,
          shift_id: 2,
          season_id: 20252026,
          game_date: "2025-10-07",
          player_id: 92,
          team_id: 10,
          period: 1,
          shift_number: 1,
          start_seconds: 250,
          end_seconds: 350,
          duration_seconds: 100,
        },
        {
          game_id: 2025020001,
          shift_id: 3,
          season_id: 20252026,
          game_date: "2025-10-07",
          player_id: 4,
          team_id: 20,
          period: 1,
          shift_number: 1,
          start_seconds: 250,
          end_seconds: 350,
          duration_seconds: 100,
        },
      ] as any,
      {
        shooterHandednessByPlayerId: new Map([[91, "L"]]),
        goalieCatchHandByPlayerId: new Map([[31, "R"]]),
        rosterPositionByPlayerId: new Map([
          [91, "D"],
          [92, "C"],
          [4, "D"],
        ]),
      }
    );

    expect(rows[0]).toMatchObject({
      shooterRosterPosition: "D",
      shooterPositionGroup: "defense",
      isDefensemanShooter: true,
      shooterHandedness: "L",
      goalieCatchHand: "R",
      shooterGoalieHandednessMatchup: "opposite-hand",
      ownerForwardCountOnIce: 1,
      ownerDefenseCountOnIce: 1,
      opponentForwardCountOnIce: 0,
      opponentDefenseCountOnIce: 1,
      ownerSkaterDeploymentBucket: "1F-1D",
      opponentSkaterDeploymentBucket: "0F-1D",
      skaterRoleMatchupBucket: "1F-1D_vs_0F-1D",
    });
  });
});
