import { describe, expect, it } from "vitest";

import {
  buildMatchupCards,
  buildPlayerVsTeamSummary,
  buildPpShotShareRows,
  buildTeamLeaderRows,
} from "./splitsSurface";

describe("buildPpShotShareRows", () => {
  it("derives team-level PP shot share from player shot totals", () => {
    const rows = buildPpShotShareRows([
      {
        playerId: 1,
        playerName: "Shooter A",
        positionCode: "RW",
        shots: 12,
      },
      {
        playerId: 2,
        playerName: "Shooter B",
        positionCode: "D",
        shots: 8,
      },
    ]);

    expect(rows).toHaveLength(2);
    expect(rows[0]).toMatchObject({
      playerId: 1,
      ppShots: 12,
    });
    expect(rows[0].ppShotSharePct).toBeCloseTo(0.6);
    expect(rows[1].ppShotSharePct).toBeCloseTo(0.4);
  });
});

describe("buildTeamLeaderRows", () => {
  it("adds PP shot share into the fantasy pulse ranking", () => {
    const leaders = buildTeamLeaderRows({
      leaderRows: [
        {
          playerId: 10,
          playerName: "Driver One",
          positionCode: "C",
          teamLabel: "EDM",
          shotsPer60: 11,
          totalPointsPer60: 3,
          ixgPer60: 1.4,
        },
        {
          playerId: 11,
          playerName: "Driver Two",
          positionCode: "RW",
          teamLabel: "EDM",
          shotsPer60: 10,
          totalPointsPer60: 2.8,
          ixgPer60: 1.3,
        },
      ],
      ppShotShareRows: [
        {
          playerId: 11,
          playerName: "Driver Two",
          positionCode: "RW",
          ppShots: 14,
          ppShotSharePct: 0.7,
        },
        {
          playerId: 10,
          playerName: "Driver One",
          positionCode: "C",
          ppShots: 6,
          ppShotSharePct: 0.3,
        },
      ],
    });

    expect(leaders[0]?.playerId).toBe(11);
    expect(leaders[0]?.ppShotSharePct).toBeCloseTo(0.7);
    expect(leaders[0]?.fantasyPulse).toBeGreaterThan(
      leaders[1]?.fantasyPulse ?? 0
    );
  });
});

describe("buildMatchupCards", () => {
  it("creates L10 offense and special-teams comparison cards", () => {
    const cards = buildMatchupCards({
      teamRow: {
        rowKey: "team:1",
        teamId: 1,
        teamLabel: "NJD",
        gamesPlayed: 10,
        toiSeconds: 6000,
        toiPerGameSeconds: 600,
        wins: 0,
        losses: 0,
        otl: 0,
        rowWins: 0,
        points: 0,
        cf: 0,
        ca: 0,
        cfPct: null,
        ff: 0,
        fa: 0,
        ffPct: null,
        sf: 34,
        sa: 0,
        sfPct: null,
        gf: 4,
        ga: 0,
        gfPct: null,
        xgf: 0,
        xga: 0,
        xgfPct: null,
        scf: 0,
        sca: 0,
        scfPct: null,
        scsf: 0,
        scsa: 0,
        scsfPct: null,
        scgf: 0,
        scga: 0,
        scgfPct: null,
        scshPct: null,
        scsvPct: null,
        hdcf: 0,
        hdca: 0,
        hdcfPct: null,
        hdsf: 0,
        hdsa: 0,
        hdsfPct: null,
        hdgf: 0,
        hdga: 0,
        hdgfPct: null,
        hdshPct: null,
        hdsvPct: null,
        mdcf: 0,
        mdca: 0,
        mdcfPct: null,
        mdsf: 0,
        mdsa: 0,
        mdsfPct: null,
        mdgf: 0,
        mdga: 0,
        mdgfPct: null,
        mdshPct: null,
        mdsvPct: null,
        ldcf: 0,
        ldca: 0,
        ldcfPct: null,
        ldsf: 0,
        ldsa: 0,
        ldsfPct: null,
        ldgf: 0,
        ldga: 0,
        ldgfPct: null,
        ldshPct: null,
        ldsvPct: null,
        shPct: null,
        svPct: null,
        pdo: null,
      },
      opponentRow: {
        rowKey: "team:2",
        teamId: 2,
        teamLabel: "NYI",
        gamesPlayed: 10,
        toiSeconds: 6000,
        toiPerGameSeconds: 600,
        wins: 0,
        losses: 0,
        otl: 0,
        rowWins: 0,
        points: 0,
        cf: 0,
        ca: 0,
        cfPct: null,
        ff: 0,
        fa: 0,
        ffPct: null,
        sf: 0,
        sa: 29,
        sfPct: null,
        gf: 0,
        ga: 2.6,
        gfPct: null,
        xgf: 0,
        xga: 0,
        xgfPct: null,
        scf: 0,
        sca: 0,
        scfPct: null,
        scsf: 0,
        scsa: 0,
        scsfPct: null,
        scgf: 0,
        scga: 0,
        scgfPct: null,
        scshPct: null,
        scsvPct: null,
        hdcf: 0,
        hdca: 0,
        hdcfPct: null,
        hdsf: 0,
        hdsa: 0,
        hdsfPct: null,
        hdgf: 0,
        hdga: 0,
        hdgfPct: null,
        hdshPct: null,
        hdsvPct: null,
        mdcf: 0,
        mdca: 0,
        mdcfPct: null,
        mdsf: 0,
        mdsa: 0,
        mdsfPct: null,
        mdgf: 0,
        mdga: 0,
        mdgfPct: null,
        mdshPct: null,
        mdsvPct: null,
        ldcf: 0,
        ldca: 0,
        ldcfPct: null,
        ldsf: 0,
        ldsa: 0,
        ldsfPct: null,
        ldgf: 0,
        ldga: 0,
        ldgfPct: null,
        ldshPct: null,
        ldsvPct: null,
        shPct: null,
        svPct: null,
        pdo: null,
      },
      teamPowerPlayRow: {
        rowKey: "pp:1",
        teamId: 1,
        teamLabel: "NJD",
        gamesPlayed: 10,
        toiSeconds: 600,
        toiPerGameSeconds: 60,
        wins: 0,
        losses: 0,
        otl: 0,
        rowWins: 0,
        points: 0,
        cf: 0,
        ca: 0,
        cfPct: null,
        ff: 0,
        fa: 0,
        ffPct: null,
        sf: 0,
        sa: 0,
        sfPct: null,
        gf: 0,
        ga: 0,
        gfPct: null,
        xgf: 0,
        xga: 0,
        xgfPct: null,
        scf: 0,
        sca: 0,
        scfPct: null,
        scsf: 0,
        scsa: 0,
        scsfPct: null,
        scgf: 0,
        scga: 0,
        scgfPct: null,
        scshPct: null,
        scsvPct: null,
        hdcf: 0,
        hdca: 0,
        hdcfPct: null,
        hdsf: 0,
        hdsa: 0,
        hdsfPct: null,
        hdgf: 0,
        hdga: 0,
        hdgfPct: null,
        hdshPct: null,
        hdsvPct: null,
        mdcf: 0,
        mdca: 0,
        mdcfPct: null,
        mdsf: 0,
        mdsa: 0,
        mdsfPct: null,
        mdgf: 0,
        mdga: 0,
        mdgfPct: null,
        mdshPct: null,
        mdsvPct: null,
        ldcf: 0,
        ldca: 0,
        ldcfPct: null,
        ldsf: 0,
        ldsa: 0,
        ldsfPct: null,
        ldgf: 0,
        ldga: 0,
        ldgfPct: null,
        ldshPct: null,
        ldsvPct: null,
        shPct: null,
        svPct: null,
        pdo: null,
        gfPer60: 8.2,
      },
      opponentPenaltyKillRow: {
        rowKey: "pk:2",
        teamId: 2,
        teamLabel: "NYI",
        gamesPlayed: 10,
        toiSeconds: 600,
        toiPerGameSeconds: 60,
        wins: 0,
        losses: 0,
        otl: 0,
        rowWins: 0,
        points: 0,
        cf: 0,
        ca: 0,
        cfPct: null,
        ff: 0,
        fa: 0,
        ffPct: null,
        sf: 0,
        sa: 0,
        sfPct: null,
        gf: 0,
        ga: 0,
        gfPct: null,
        xgf: 0,
        xga: 0,
        xgfPct: null,
        scf: 0,
        sca: 0,
        scfPct: null,
        scsf: 0,
        scsa: 0,
        scsfPct: null,
        scgf: 0,
        scga: 0,
        scgfPct: null,
        scshPct: null,
        scsvPct: null,
        hdcf: 0,
        hdca: 0,
        hdcfPct: null,
        hdsf: 0,
        hdsa: 0,
        hdsfPct: null,
        hdgf: 0,
        hdga: 0,
        hdgfPct: null,
        hdshPct: null,
        hdsvPct: null,
        mdcf: 0,
        mdca: 0,
        mdcfPct: null,
        mdsf: 0,
        mdsa: 0,
        mdsfPct: null,
        mdgf: 0,
        mdga: 0,
        mdgfPct: null,
        mdshPct: null,
        mdsvPct: null,
        ldcf: 0,
        ldca: 0,
        ldcfPct: null,
        ldsf: 0,
        ldsa: 0,
        ldsfPct: null,
        ldgf: 0,
        ldga: 0,
        ldgfPct: null,
        ldshPct: null,
        ldsvPct: null,
        shPct: null,
        svPct: null,
        pdo: null,
        gaPer60: 5.6,
      },
    });

    expect(cards.map((card) => card.key)).toEqual([
      "shots",
      "goals",
      "powerPlay",
    ]);
    expect(cards[0]?.edge).toBe("favorable");
    expect(cards[2]?.edge).toBe("favorable");
  });
});

describe("buildPlayerVsTeamSummary", () => {
  it("packages a player baseline and opponent split into one comparison payload", () => {
    const summary = buildPlayerVsTeamSummary({
      baselineRow: {
        playerId: 97,
        playerName: "Star Skater",
        teamLabel: "EDM",
        gamesPlayed: 68,
        toiPerGameSeconds: 1210,
        shotsPer60: 10.2,
        totalPointsPer60: 4.0,
        ixgPer60: 1.3,
        goalsPer60: 1.4,
      },
      versusOpponentRow: {
        playerId: 97,
        playerName: "Star Skater",
        teamLabel: "EDM",
        gamesPlayed: 4,
        toiPerGameSeconds: 1225,
        shotsPer60: 11.1,
        totalPointsPer60: 4.8,
        ixgPer60: 1.5,
        goalsPer60: 1.8,
      },
      opponentLabel: "VAN",
      ppShotSharePct: 0.41,
    });

    expect(summary).toMatchObject({
      playerId: 97,
      playerName: "Star Skater",
      opponentLabel: "VAN",
      season: {
        gamesPlayed: 68,
        ppShotSharePct: 0.41,
      },
      versusOpponent: {
        gamesPlayed: 4,
        shotsPer60: 11.1,
      },
    });
  });
});
