-- Projection engine: structured roster/news overrides
-- Used as an input to adjust roles/usage assumptions and goalie starter probabilities.

CREATE TABLE IF NOT EXISTS roster_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    effective_to TIMESTAMPTZ NULL,

    team_id SMALLINT NULL REFERENCES teams(id),
    player_id BIGINT NULL REFERENCES players(id),

    event_type TEXT NOT NULL,
    confidence NUMERIC NOT NULL DEFAULT 0.5,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_text TEXT NULL,

    CONSTRAINT roster_events_confidence_check CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT roster_events_type_check CHECK (
        event_type IN (
            'INJURY_OUT',
            'DTD',
            'RETURN',
            'CALLUP',
            'SENDDOWN',
            'LINE_CHANGE',
            'PP_UNIT_CHANGE',
            'GOALIE_START_CONFIRMED',
            'GOALIE_START_LIKELY'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_roster_events_team_effective_from
ON roster_events (team_id, effective_from DESC);

CREATE INDEX IF NOT EXISTS idx_roster_events_player_effective_from
ON roster_events (player_id, effective_from DESC);

