-- Add true 5v5 skater NST gamelog tables.
-- These mirror the existing NST skater gamelog table families but use
-- Natural Stat Trick playerteams.php?sit=5v5 source pages.

CREATE TABLE IF NOT EXISTS public.nst_gamelog_5v5_counts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES public.players(id),
  season INTEGER NOT NULL,
  date_scraped DATE NOT NULL,
  gp INTEGER,
  toi INTEGER,
  goals INTEGER,
  total_assists INTEGER,
  first_assists INTEGER,
  second_assists INTEGER,
  total_points INTEGER,
  ipp DOUBLE PRECISION,
  shots INTEGER,
  sh_percentage DOUBLE PRECISION,
  ixg DOUBLE PRECISION,
  icf INTEGER,
  iff INTEGER,
  iscfs INTEGER,
  hdcf INTEGER,
  rush_attempts INTEGER,
  rebounds_created INTEGER,
  pim INTEGER,
  total_penalties INTEGER,
  minor_penalties INTEGER,
  major_penalties INTEGER,
  misconduct_penalties INTEGER,
  penalties_drawn INTEGER,
  giveaways INTEGER,
  takeaways INTEGER,
  hits INTEGER,
  hits_taken INTEGER,
  shots_blocked INTEGER,
  faceoffs_won INTEGER,
  faceoffs_lost INTEGER,
  faceoffs_percentage DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT nst_gamelog_5v5_counts_unique UNIQUE (player_id, date_scraped)
);

CREATE TABLE IF NOT EXISTS public.nst_gamelog_5v5_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES public.players(id),
  season INTEGER NOT NULL,
  date_scraped DATE NOT NULL,
  gp INTEGER,
  toi INTEGER,
  toi_per_gp DOUBLE PRECISION,
  goals_per_60 DOUBLE PRECISION,
  total_assists_per_60 DOUBLE PRECISION,
  first_assists_per_60 DOUBLE PRECISION,
  second_assists_per_60 DOUBLE PRECISION,
  total_points_per_60 DOUBLE PRECISION,
  ipp DOUBLE PRECISION,
  shots_per_60 DOUBLE PRECISION,
  sh_percentage DOUBLE PRECISION,
  ixg_per_60 DOUBLE PRECISION,
  icf_per_60 DOUBLE PRECISION,
  iff_per_60 DOUBLE PRECISION,
  iscfs_per_60 DOUBLE PRECISION,
  hdcf_per_60 DOUBLE PRECISION,
  rush_attempts_per_60 DOUBLE PRECISION,
  rebounds_created_per_60 DOUBLE PRECISION,
  pim_per_60 DOUBLE PRECISION,
  total_penalties_per_60 DOUBLE PRECISION,
  minor_penalties_per_60 DOUBLE PRECISION,
  major_penalties_per_60 DOUBLE PRECISION,
  misconduct_penalties_per_60 DOUBLE PRECISION,
  penalties_drawn_per_60 DOUBLE PRECISION,
  giveaways_per_60 DOUBLE PRECISION,
  takeaways_per_60 DOUBLE PRECISION,
  hits_per_60 DOUBLE PRECISION,
  hits_taken_per_60 DOUBLE PRECISION,
  shots_blocked_per_60 DOUBLE PRECISION,
  faceoffs_won_per_60 DOUBLE PRECISION,
  faceoffs_lost_per_60 DOUBLE PRECISION,
  faceoffs_percentage DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT nst_gamelog_5v5_rates_unique UNIQUE (player_id, date_scraped)
);

CREATE TABLE IF NOT EXISTS public.nst_gamelog_5v5_counts_oi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES public.players(id),
  season INTEGER NOT NULL,
  date_scraped DATE NOT NULL,
  gp INTEGER,
  toi INTEGER,
  cf INTEGER,
  ca INTEGER,
  cf_pct DOUBLE PRECISION,
  ff INTEGER,
  fa INTEGER,
  ff_pct DOUBLE PRECISION,
  sf INTEGER,
  sa INTEGER,
  sf_pct DOUBLE PRECISION,
  gf INTEGER,
  ga INTEGER,
  gf_pct DOUBLE PRECISION,
  xgf DOUBLE PRECISION,
  xga DOUBLE PRECISION,
  xgf_pct DOUBLE PRECISION,
  scf INTEGER,
  sca INTEGER,
  scf_pct DOUBLE PRECISION,
  hdcf INTEGER,
  hdca INTEGER,
  hdcf_pct DOUBLE PRECISION,
  hdgf INTEGER,
  hdga INTEGER,
  hdgf_pct DOUBLE PRECISION,
  mdcf INTEGER,
  mdca INTEGER,
  mdcf_pct DOUBLE PRECISION,
  mdgf INTEGER,
  mdga INTEGER,
  mdgf_pct DOUBLE PRECISION,
  ldcf INTEGER,
  ldca INTEGER,
  ldcf_pct DOUBLE PRECISION,
  ldgf INTEGER,
  ldga INTEGER,
  ldgf_pct DOUBLE PRECISION,
  on_ice_sh_pct DOUBLE PRECISION,
  on_ice_sv_pct DOUBLE PRECISION,
  pdo DOUBLE PRECISION,
  off_zone_starts INTEGER,
  neu_zone_starts INTEGER,
  def_zone_starts INTEGER,
  on_the_fly_starts DOUBLE PRECISION,
  off_zone_start_pct DOUBLE PRECISION,
  off_zone_faceoffs INTEGER,
  neu_zone_faceoffs INTEGER,
  def_zone_faceoffs INTEGER,
  off_zone_faceoff_pct DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT nst_gamelog_5v5_counts_oi_unique UNIQUE (player_id, date_scraped)
);

CREATE TABLE IF NOT EXISTS public.nst_gamelog_5v5_rates_oi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES public.players(id),
  season INTEGER NOT NULL,
  date_scraped DATE NOT NULL,
  gp INTEGER,
  toi INTEGER,
  toi_per_gp DOUBLE PRECISION,
  cf_per_60 DOUBLE PRECISION,
  ca_per_60 DOUBLE PRECISION,
  cf_pct DOUBLE PRECISION,
  ff_per_60 DOUBLE PRECISION,
  fa_per_60 DOUBLE PRECISION,
  ff_pct DOUBLE PRECISION,
  sf_per_60 DOUBLE PRECISION,
  sa_per_60 DOUBLE PRECISION,
  sf_pct DOUBLE PRECISION,
  gf_per_60 DOUBLE PRECISION,
  ga_per_60 DOUBLE PRECISION,
  gf_pct DOUBLE PRECISION,
  xgf_per_60 DOUBLE PRECISION,
  xga_per_60 DOUBLE PRECISION,
  xgf_pct DOUBLE PRECISION,
  scf_per_60 DOUBLE PRECISION,
  sca_per_60 DOUBLE PRECISION,
  scf_pct DOUBLE PRECISION,
  hdcf_per_60 DOUBLE PRECISION,
  hdca_per_60 DOUBLE PRECISION,
  hdcf_pct DOUBLE PRECISION,
  hdgf_per_60 DOUBLE PRECISION,
  hdga_per_60 DOUBLE PRECISION,
  hdgf_pct DOUBLE PRECISION,
  mdcf_per_60 DOUBLE PRECISION,
  mdca_per_60 DOUBLE PRECISION,
  mdcf_pct DOUBLE PRECISION,
  mdgf_per_60 DOUBLE PRECISION,
  mdga_per_60 DOUBLE PRECISION,
  mdgf_pct DOUBLE PRECISION,
  ldcf_per_60 DOUBLE PRECISION,
  ldca_per_60 DOUBLE PRECISION,
  ldcf_pct DOUBLE PRECISION,
  ldgf_per_60 DOUBLE PRECISION,
  ldga_per_60 DOUBLE PRECISION,
  ldgf_pct DOUBLE PRECISION,
  on_ice_sh_pct DOUBLE PRECISION,
  on_ice_sv_pct DOUBLE PRECISION,
  pdo DOUBLE PRECISION,
  off_zone_starts_per_60 DOUBLE PRECISION,
  neu_zone_starts_per_60 DOUBLE PRECISION,
  def_zone_starts_per_60 DOUBLE PRECISION,
  on_the_fly_starts_per_60 DOUBLE PRECISION,
  off_zone_start_pct DOUBLE PRECISION,
  off_zone_faceoffs_per_60 DOUBLE PRECISION,
  neu_zone_faceoffs_per_60 DOUBLE PRECISION,
  def_zone_faceoffs_per_60 DOUBLE PRECISION,
  off_zone_faceoff_pct DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT nst_gamelog_5v5_rates_oi_unique UNIQUE (player_id, date_scraped)
);

CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_counts_date
  ON public.nst_gamelog_5v5_counts USING btree (date_scraped DESC);
CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_counts_season
  ON public.nst_gamelog_5v5_counts USING btree (season, date_scraped DESC);

CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_rates_date
  ON public.nst_gamelog_5v5_rates USING btree (date_scraped DESC);
CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_rates_season
  ON public.nst_gamelog_5v5_rates USING btree (season, date_scraped DESC);

CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_counts_oi_date
  ON public.nst_gamelog_5v5_counts_oi USING btree (date_scraped DESC);
CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_counts_oi_season
  ON public.nst_gamelog_5v5_counts_oi USING btree (season, date_scraped DESC);

CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_rates_oi_date
  ON public.nst_gamelog_5v5_rates_oi USING btree (date_scraped DESC);
CREATE INDEX IF NOT EXISTS idx_nst_gamelog_5v5_rates_oi_season
  ON public.nst_gamelog_5v5_rates_oi USING btree (season, date_scraped DESC);

REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON
  public.nst_gamelog_5v5_counts,
  public.nst_gamelog_5v5_rates,
  public.nst_gamelog_5v5_counts_oi,
  public.nst_gamelog_5v5_rates_oi
FROM anon, authenticated;

GRANT SELECT ON
  public.nst_gamelog_5v5_counts,
  public.nst_gamelog_5v5_rates,
  public.nst_gamelog_5v5_counts_oi,
  public.nst_gamelog_5v5_rates_oi
TO anon, authenticated;
