-- Broader contract cleanup for rolling_player_game_metrics.
-- This supersedes the March 10, 2026 GP-only migration as the active
-- remediation migration while leaving that earlier migration intact as
-- historical context.

ALTER TABLE public.rolling_player_game_metrics
ADD COLUMN IF NOT EXISTS season_participation_pct double precision NULL,
ADD COLUMN IF NOT EXISTS three_year_participation_pct double precision NULL,
ADD COLUMN IF NOT EXISTS career_participation_pct double precision NULL,
ADD COLUMN IF NOT EXISTS participation_pct_last3_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS participation_pct_last5_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS participation_pct_last10_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS participation_pct_last20_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS season_participation_games integer NULL,
ADD COLUMN IF NOT EXISTS three_year_participation_games integer NULL,
ADD COLUMN IF NOT EXISTS career_participation_games integer NULL,
ADD COLUMN IF NOT EXISTS participation_games_last3_team_games integer NULL,
ADD COLUMN IF NOT EXISTS participation_games_last5_team_games integer NULL,
ADD COLUMN IF NOT EXISTS participation_games_last10_team_games integer NULL,
ADD COLUMN IF NOT EXISTS participation_games_last20_team_games integer NULL;

ALTER TABLE public.rolling_player_game_metrics
ADD COLUMN IF NOT EXISTS shooting_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_all double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_season double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS ipp_career double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS cf_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_all double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_season double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS ff_pct_career double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_all double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_season double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS pdo_career double precision NULL;

ALTER TABLE public.rolling_player_game_metrics
ADD COLUMN IF NOT EXISTS sog_per_60_all double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_season double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_career double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_all double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_season double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_career double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_all double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_season double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_career double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_all double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_season double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_career double precision NULL;

ALTER TABLE public.rolling_player_game_metrics
ADD COLUMN IF NOT EXISTS shooting_pct_goals_season integer NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_shots_season integer NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_goals_3ya integer NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_shots_3ya integer NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_goals_career integer NULL,
ADD COLUMN IF NOT EXISTS shooting_pct_shots_career integer NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_ixg_season double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_shots_season integer NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_ixg_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_shots_3ya integer NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_ixg_career double precision NULL,
ADD COLUMN IF NOT EXISTS expected_sh_pct_shots_career integer NULL,
ADD COLUMN IF NOT EXISTS cf_pct_cf_season integer NULL,
ADD COLUMN IF NOT EXISTS cf_pct_ca_season integer NULL,
ADD COLUMN IF NOT EXISTS cf_pct_cf_3ya integer NULL,
ADD COLUMN IF NOT EXISTS cf_pct_ca_3ya integer NULL,
ADD COLUMN IF NOT EXISTS cf_pct_cf_career integer NULL,
ADD COLUMN IF NOT EXISTS cf_pct_ca_career integer NULL,
ADD COLUMN IF NOT EXISTS ff_pct_ff_season integer NULL,
ADD COLUMN IF NOT EXISTS ff_pct_fa_season integer NULL,
ADD COLUMN IF NOT EXISTS ff_pct_ff_3ya integer NULL,
ADD COLUMN IF NOT EXISTS ff_pct_fa_3ya integer NULL,
ADD COLUMN IF NOT EXISTS ff_pct_ff_career integer NULL,
ADD COLUMN IF NOT EXISTS ff_pct_fa_career integer NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_shots_season integer NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_toi_seconds_season double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_shots_3ya integer NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_toi_seconds_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_shots_career integer NULL,
ADD COLUMN IF NOT EXISTS sog_per_60_toi_seconds_career double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_ixg_season double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_toi_seconds_season double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_ixg_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_toi_seconds_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_ixg_career double precision NULL,
ADD COLUMN IF NOT EXISTS ixg_per_60_toi_seconds_career double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_hits_season integer NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_toi_seconds_season double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_hits_3ya integer NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_toi_seconds_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_hits_career integer NULL,
ADD COLUMN IF NOT EXISTS hits_per_60_toi_seconds_career double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_blocks_season integer NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_toi_seconds_season double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_blocks_3ya integer NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_toi_seconds_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_blocks_career integer NULL,
ADD COLUMN IF NOT EXISTS blocks_per_60_toi_seconds_career double precision NULL;

ALTER TABLE public.rolling_player_game_metrics
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_all integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_all integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_last3 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_last3 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_last5 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_last5 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_last10 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_last10 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_last20 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_last20 integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_season integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_season integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_3ya integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_3ya integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_primary_points_career integer NULL,
ADD COLUMN IF NOT EXISTS primary_points_pct_points_career integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_all integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_all integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_last3 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_last3 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_last5 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_last5 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_last10 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_last10 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_last20 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_last20 integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_season integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_season integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_3ya integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_3ya integer NULL,
ADD COLUMN IF NOT EXISTS ipp_points_career integer NULL,
ADD COLUMN IF NOT EXISTS ipp_on_ice_goals_for_career integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_all integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_all integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_last3 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_last3 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_last5 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_last5 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_last10 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_last10 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_last20 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_last20 integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_season integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_season integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_3ya integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_3ya integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_goals_for_career integer NULL,
ADD COLUMN IF NOT EXISTS on_ice_sh_pct_shots_for_career integer NULL;

ALTER TABLE public.rolling_player_game_metrics
ADD COLUMN IF NOT EXISTS pdo_goals_for_all integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_all integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_all integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_all integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_for_last3 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_last3 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_last3 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_last3 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_for_last5 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_last5 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_last5 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_last5 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_for_last10 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_last10 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_last10 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_last10 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_for_last20 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_last20 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_last20 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_last20 integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_for_season integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_season integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_season integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_season integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_for_3ya integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_3ya integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_3ya integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_3ya integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_for_career integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_for_career integer NULL,
ADD COLUMN IF NOT EXISTS pdo_goals_against_career integer NULL,
ADD COLUMN IF NOT EXISTS pdo_shots_against_career integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_all integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_all integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_all integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_last3 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_last3 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_last3 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_last5 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_last5 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_last5 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_last10 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_last10 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_last10 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_last20 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_last20 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_last20 integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_season integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_season integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_season integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_3ya integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_3ya integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_3ya integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_off_zone_starts_career integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_def_zone_starts_career integer NULL,
ADD COLUMN IF NOT EXISTS oz_start_pct_neutral_zone_starts_career integer NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_all double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_all double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_last3 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_last5 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_last10 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_last20 double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_season double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_season double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_3ya double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_player_pp_toi_career double precision NULL,
ADD COLUMN IF NOT EXISTS pp_share_pct_team_pp_toi_career double precision NULL;
