alter table public.rolling_player_game_metrics
  add column if not exists goals_per_60_total_all double precision null,
  add column if not exists goals_per_60_avg_all double precision null,
  add column if not exists goals_per_60_total_last3 double precision null,
  add column if not exists goals_per_60_avg_last3 double precision null,
  add column if not exists goals_per_60_total_last5 double precision null,
  add column if not exists goals_per_60_avg_last5 double precision null,
  add column if not exists goals_per_60_total_last10 double precision null,
  add column if not exists goals_per_60_avg_last10 double precision null,
  add column if not exists goals_per_60_total_last20 double precision null,
  add column if not exists goals_per_60_avg_last20 double precision null,
  add column if not exists goals_per_60_avg_season double precision null,
  add column if not exists goals_per_60_avg_3ya double precision null,
  add column if not exists goals_per_60_avg_career double precision null,
  add column if not exists goals_per_60_all double precision null,
  add column if not exists goals_per_60_last3 double precision null,
  add column if not exists goals_per_60_last5 double precision null,
  add column if not exists goals_per_60_last10 double precision null,
  add column if not exists goals_per_60_last20 double precision null,
  add column if not exists goals_per_60_season double precision null,
  add column if not exists goals_per_60_3ya double precision null,
  add column if not exists goals_per_60_career double precision null,
  add column if not exists goals_per_60_goals_season integer null,
  add column if not exists goals_per_60_toi_seconds_season double precision null,
  add column if not exists goals_per_60_goals_3ya integer null,
  add column if not exists goals_per_60_toi_seconds_3ya double precision null,
  add column if not exists goals_per_60_goals_career integer null,
  add column if not exists goals_per_60_toi_seconds_career double precision null,
  add column if not exists assists_per_60_total_all double precision null,
  add column if not exists assists_per_60_avg_all double precision null,
  add column if not exists assists_per_60_total_last3 double precision null,
  add column if not exists assists_per_60_avg_last3 double precision null,
  add column if not exists assists_per_60_total_last5 double precision null,
  add column if not exists assists_per_60_avg_last5 double precision null,
  add column if not exists assists_per_60_total_last10 double precision null,
  add column if not exists assists_per_60_avg_last10 double precision null,
  add column if not exists assists_per_60_total_last20 double precision null,
  add column if not exists assists_per_60_avg_last20 double precision null,
  add column if not exists assists_per_60_avg_season double precision null,
  add column if not exists assists_per_60_avg_3ya double precision null,
  add column if not exists assists_per_60_avg_career double precision null,
  add column if not exists assists_per_60_all double precision null,
  add column if not exists assists_per_60_last3 double precision null,
  add column if not exists assists_per_60_last5 double precision null,
  add column if not exists assists_per_60_last10 double precision null,
  add column if not exists assists_per_60_last20 double precision null,
  add column if not exists assists_per_60_season double precision null,
  add column if not exists assists_per_60_3ya double precision null,
  add column if not exists assists_per_60_career double precision null,
  add column if not exists assists_per_60_assists_season integer null,
  add column if not exists assists_per_60_toi_seconds_season double precision null,
  add column if not exists assists_per_60_assists_3ya integer null,
  add column if not exists assists_per_60_toi_seconds_3ya double precision null,
  add column if not exists assists_per_60_assists_career integer null,
  add column if not exists assists_per_60_toi_seconds_career double precision null,
  add column if not exists primary_assists_per_60_total_all double precision null,
  add column if not exists primary_assists_per_60_avg_all double precision null,
  add column if not exists primary_assists_per_60_total_last3 double precision null,
  add column if not exists primary_assists_per_60_avg_last3 double precision null,
  add column if not exists primary_assists_per_60_total_last5 double precision null,
  add column if not exists primary_assists_per_60_avg_last5 double precision null,
  add column if not exists primary_assists_per_60_total_last10 double precision null,
  add column if not exists primary_assists_per_60_avg_last10 double precision null,
  add column if not exists primary_assists_per_60_total_last20 double precision null,
  add column if not exists primary_assists_per_60_avg_last20 double precision null,
  add column if not exists primary_assists_per_60_avg_season double precision null,
  add column if not exists primary_assists_per_60_avg_3ya double precision null,
  add column if not exists primary_assists_per_60_avg_career double precision null,
  add column if not exists primary_assists_per_60_all double precision null,
  add column if not exists primary_assists_per_60_last3 double precision null,
  add column if not exists primary_assists_per_60_last5 double precision null,
  add column if not exists primary_assists_per_60_last10 double precision null,
  add column if not exists primary_assists_per_60_last20 double precision null,
  add column if not exists primary_assists_per_60_season double precision null,
  add column if not exists primary_assists_per_60_3ya double precision null,
  add column if not exists primary_assists_per_60_career double precision null,
  add column if not exists primary_assists_per_60_primary_assists_season integer null,
  add column if not exists primary_assists_per_60_toi_seconds_season double precision null,
  add column if not exists primary_assists_per_60_primary_assists_3ya integer null,
  add column if not exists primary_assists_per_60_toi_seconds_3ya double precision null,
  add column if not exists primary_assists_per_60_primary_assists_career integer null,
  add column if not exists primary_assists_per_60_toi_seconds_career double precision null,
  add column if not exists secondary_assists_per_60_total_all double precision null,
  add column if not exists secondary_assists_per_60_avg_all double precision null,
  add column if not exists secondary_assists_per_60_total_last3 double precision null,
  add column if not exists secondary_assists_per_60_avg_last3 double precision null,
  add column if not exists secondary_assists_per_60_total_last5 double precision null,
  add column if not exists secondary_assists_per_60_avg_last5 double precision null,
  add column if not exists secondary_assists_per_60_total_last10 double precision null,
  add column if not exists secondary_assists_per_60_avg_last10 double precision null,
  add column if not exists secondary_assists_per_60_total_last20 double precision null,
  add column if not exists secondary_assists_per_60_avg_last20 double precision null,
  add column if not exists secondary_assists_per_60_avg_season double precision null,
  add column if not exists secondary_assists_per_60_avg_3ya double precision null,
  add column if not exists secondary_assists_per_60_avg_career double precision null,
  add column if not exists secondary_assists_per_60_all double precision null,
  add column if not exists secondary_assists_per_60_last3 double precision null,
  add column if not exists secondary_assists_per_60_last5 double precision null,
  add column if not exists secondary_assists_per_60_last10 double precision null,
  add column if not exists secondary_assists_per_60_last20 double precision null,
  add column if not exists secondary_assists_per_60_season double precision null,
  add column if not exists secondary_assists_per_60_3ya double precision null,
  add column if not exists secondary_assists_per_60_career double precision null,
  add column if not exists secondary_assists_per_60_secondary_assists_season integer null,
  add column if not exists secondary_assists_per_60_toi_seconds_season double precision null,
  add column if not exists secondary_assists_per_60_secondary_assists_3ya integer null,
  add column if not exists secondary_assists_per_60_toi_seconds_3ya double precision null,
  add column if not exists secondary_assists_per_60_secondary_assists_career integer null,
  add column if not exists secondary_assists_per_60_toi_seconds_career double precision null;
