ALTER TABLE public.rolling_player_game_metrics
ADD COLUMN IF NOT EXISTS season_availability_pct double precision NULL,
ADD COLUMN IF NOT EXISTS three_year_availability_pct double precision NULL,
ADD COLUMN IF NOT EXISTS career_availability_pct double precision NULL,
ADD COLUMN IF NOT EXISTS availability_pct_last3_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS availability_pct_last5_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS availability_pct_last10_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS availability_pct_last20_team_games double precision NULL,
ADD COLUMN IF NOT EXISTS season_games_played integer NULL,
ADD COLUMN IF NOT EXISTS season_team_games_available integer NULL,
ADD COLUMN IF NOT EXISTS three_year_games_played integer NULL,
ADD COLUMN IF NOT EXISTS three_year_team_games_available integer NULL,
ADD COLUMN IF NOT EXISTS career_games_played integer NULL,
ADD COLUMN IF NOT EXISTS career_team_games_available integer NULL,
ADD COLUMN IF NOT EXISTS games_played_last3_team_games integer NULL,
ADD COLUMN IF NOT EXISTS team_games_available_last3 integer NULL,
ADD COLUMN IF NOT EXISTS games_played_last5_team_games integer NULL,
ADD COLUMN IF NOT EXISTS team_games_available_last5 integer NULL,
ADD COLUMN IF NOT EXISTS games_played_last10_team_games integer NULL,
ADD COLUMN IF NOT EXISTS team_games_available_last10 integer NULL,
ADD COLUMN IF NOT EXISTS games_played_last20_team_games integer NULL,
ADD COLUMN IF NOT EXISTS team_games_available_last20 integer NULL,
ADD COLUMN IF NOT EXISTS gp_semantic_type text NULL;
