import { z } from "zod";

const finite = z.number().finite().min(-1_000_000).max(1_000_000);
const boundedRecord = <T extends z.ZodTypeAny>(value: T, max = 80) => z.record(z.string().max(100), value).refine((record) => Object.keys(record).length <= max, `At most ${max} values are allowed.`);
const player = z.object({ id: z.string().trim().min(1).max(100), name: z.string().trim().min(1).max(200), role: z.enum(["skater", "goalie"]), eligiblePositions: z.array(z.string().trim().min(1).max(12)).min(1).max(12), teamAbbreviation: z.string().trim().min(1).max(8).nullable(), projectionSeason: z.string().trim().min(1).max(40), status: z.enum(["active", "bench", "ir", "ir+", "na", "inactive"]).optional(), globalVorp: finite, rankValue: finite, projectedPoints: finite.optional(), available: z.boolean().optional(), drafted: z.boolean().optional(), categoryValues: boundedRecord(finite.nullable()).optional() }).strict();
const projection = z.object({ id: z.string().trim().min(1).max(120), version: z.string().trim().min(1).max(120), origin: z.enum(["server", "saved_private_import"]), privateImports: z.array(z.object({ id: z.string().uuid(), contentFingerprint: z.string().regex(/^scenario-v1-[a-f0-9]{32}$/) }).strict()).max(100).optional() }).strict().superRefine((value, context) => { if (value.origin === "saved_private_import" && !value.privateImports?.length) context.addIssue({ code: z.ZodIssueCode.custom, message: "Saved private projections require owned import references." }); if (value.origin === "server" && value.privateImports?.length) context.addIssue({ code: z.ZodIssueCode.custom, message: "Server projections cannot reference private imports." }); });
const schedule = z.object({ season: z.string().trim().regex(/^\d{8}$/), gameKey: z.string().trim().min(1).max(40).optional(), startWeek: z.number().int().min(1).max(40), endWeek: z.number().int().min(1).max(40), lineupMode: z.enum(["daily", "weekly"]), rosterSlots: boundedRecord(z.number().int().min(0).max(30), 30) }).strict().refine((value) => value.endWeek >= value.startWeek && value.endWeek - value.startWeek < 40, "The matchup-week range is invalid.");
export const scenarioAnalysisSchema = z.object({ roster: z.array(player).max(60), candidateA: player, candidateB: player, leagueType: z.enum(["points", "categories"]), categoryWeights: boundedRecord(finite).optional(), positionNeeds: boundedRecord(finite, 30).optional(), source: z.object({ projection, schedule }).strict() }).strict().superRefine((value, context) => { if (value.leagueType === "points" && [...value.roster, value.candidateA, value.candidateB].some((item) => item.projectedPoints === undefined)) context.addIssue({ code: z.ZodIssueCode.custom, message: "Points scenarios require projected points for every player." }); });
export const scenarioRequestSchema = z.discriminatedUnion("action", [z.object({ action: z.literal("analyze"), draftId: z.string().uuid().nullable().optional(), scenario: scenarioAnalysisSchema }).strict(), z.object({ action: z.literal("save"), name: z.string().trim().min(1).max(120), draftId: z.string().uuid().nullable().optional(), scenario: scenarioAnalysisSchema }).strict()]);
export type ScenarioAnalysisRequest = z.infer<typeof scenarioAnalysisSchema>;
