import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
const hook = vi.hoisted(() => vi.fn()); vi.mock("hooks/useDraftProScenarios", () => ({ useDraftProScenarios: hook }));
import { ScenarioComparisonWorkspace } from "./ScenarioComparisonWorkspace";
const source = { projection: { id: "public", version: "v1", origin: "server" as const }, schedule: { season: "20262027", startWeek: 1, endWeek: 1, lineupMode: "daily" as const, rosterSlots: { C: 1 } } };
const player = { id: "a", name: "Player A", role: "skater" as const, eligiblePositions: ["C"], teamAbbreviation: "AAA", projectionSeason: "20262027", globalVorp: 2, rankValue: 2, projectedPoints: 50 };
const input = { roster: [], candidateA: player, candidateB: { ...player, id: "b", name: "Player B" }, leagueType: "points" as const, source };
const result = { fingerprint: "current", baseline: { rawVorp: 0, projectedPoints: 0, categories: {} }, schedule: { state: "ready" as const, freshness: null, window: null, diagnostics: [] }, candidates: [{ id: "a", name: "Player A", rawVorpDelta: 2, rawVorpAfter: 2, projectedPointsDelta: 50, projectedPointsAfter: 50, categoryScoreDelta: null, positionNeeds: ["C"], categories: {}, dust: { activeGamesAdded: 3, marginalBenchGames: 1, unavailable: false, reason: null } }, { id: "b", name: "Player B", rawVorpDelta: 1, rawVorpAfter: 1, projectedPointsDelta: 40, projectedPointsAfter: 40, categoryScoreDelta: null, positionNeeds: [], categories: {}, dust: { activeGamesAdded: 1, marginalBenchGames: 2, unavailable: false, reason: null } }] };
afterEach(cleanup);
describe("ScenarioComparisonWorkspace", () => {
  it("owns compare, naming, save, list, and open interactions", () => { const generate = vi.fn(); const save = vi.fn(); const open = vi.fn(); hook.mockReturnValue({ result, stale: false, contextUnavailable: false, openedFingerprint: null, openedId: null, status: "idle", error: null, saved: [{ id: "saved", name: "Saved A/B", updated_at: "2026-09-07T00:00:00Z" }], generate, save, open, retry: vi.fn(), list: vi.fn() }); render(<ScenarioComparisonWorkspace eligible input={input} />); fireEvent.click(screen.getByRole("button", { name: "Compare A vs B" })); fireEvent.change(screen.getByLabelText("Scenario name"), { target: { value: "Choice" } }); fireEvent.click(screen.getByRole("button", { name: "Save scenario" })); fireEvent.click(screen.getByRole("button", { name: "Saved A/B" })); expect(generate).toHaveBeenCalledWith(input, undefined); expect(save).toHaveBeenCalledWith("Choice", input, undefined); expect(open).toHaveBeenCalledWith("saved"); expect(screen.getByText(/Baseline projected points/)).toBeTruthy(); });
  it("locks premium payloads while preserving the existing free table comparison", () => { hook.mockReturnValue({ result, stale: false, contextUnavailable: false, openedFingerprint: null, openedId: null, status: "idle", error: null, saved: [{ id: "saved", name: "Saved A/B", updated_at: "2026-09-07T00:00:00Z" }], generate: vi.fn(), save: vi.fn(), open: vi.fn(), retry: vi.fn(), list: vi.fn() }); render(<ScenarioComparisonWorkspace eligible={false} input={input} />); expect(screen.getByText(/Existing free two-player comparison remains available in the projections table/i)).toBeTruthy(); expect(screen.queryByText("Player A")).toBeNull(); expect(screen.getByRole("button", { name: "Saved A/B" }).hasAttribute("disabled")).toBe(true); });
  it("shows an opened historical result without current candidates", () => { hook.mockReturnValue({ result, stale: true, contextUnavailable: true, openedFingerprint: "saved", openedId: "saved", status: "idle", error: null, saved: [], generate: vi.fn(), save: vi.fn(), open: vi.fn(), retry: vi.fn(), list: vi.fn() }); render(<ScenarioComparisonWorkspace eligible input={null} />); expect(screen.getByText("Player A")).toBeTruthy(); expect(screen.getByText(/no matching current comparison context/i)).toBeTruthy(); expect(screen.getByText(/Saved scenario is stale/i)).toBeTruthy(); });
  it("shows saved-list progress and retries list failures independently", () => { const list = vi.fn(); hook.mockReturnValue({ result: null, stale: false, contextUnavailable: false, openedFingerprint: null, openedId: null, status: "idle", error: null, listLoading: true, listError: null, saved: [], generate: vi.fn(), save: vi.fn(), open: vi.fn(), retry: vi.fn(), list }); const { rerender } = render(<ScenarioComparisonWorkspace eligible input={input} />); expect(screen.getByText("Loading saved scenario names…")).toBeTruthy(); hook.mockReturnValue({ result: null, stale: false, contextUnavailable: false, openedFingerprint: null, openedId: null, status: "idle", error: null, listLoading: false, listError: "List failed", saved: [], generate: vi.fn(), save: vi.fn(), open: vi.fn(), retry: vi.fn(), list }); rerender(<ScenarioComparisonWorkspace eligible input={input} />); fireEvent.click(screen.getByRole("button", { name: "Retry saved list" })); expect(list).toHaveBeenCalledTimes(1); });
});
