export const teamsInfo = {
    NJD: { name: 'New Jersey Devils', primaryColor: '#000000', secondaryColor: '#a20620', jersey: '#FFFFFF', accent: '#154734', alt: '#FFFFFF', id: 1},
    NYI: { name: 'New York Islanders', primaryColor: '#003087', secondaryColor: '#FFFFFF', jersey: '#FC4C02', accent: '#000000', alt: '#FFFFFF', id: 2},
    NYR: { name: 'New York Rangers', primaryColor: '#0038A8', secondaryColor: '#FFFFFF', jersey: '#CE1126', accent: '#A2AAAD', alt: '#FFFFFF', id: 3},
    PHI: { name: 'Philadelphia Flyers', primaryColor: '#000000', secondaryColor: '#FA4616', jersey: '#FA4616', accent: '#FFFFFF', alt: '#FFFFFF', id: 4 },
    PIT: { name: 'Pittsburgh Penguins', primaryColor: '#000000', secondaryColor: '#FFB81C', jersey: '#FFFFFF', accent: '#FFB81C', alt: '#FFFFFF', id: 5 },
    BOS: { name: 'Boston Bruins', primaryColor: '#000000', secondaryColor: '#FFB81C', jersey: '#FFFFFF', accent: '#FFB81C', alt: '#FFFFFF', id: 6 },
    BUF: { name: 'Buffalo Sabres', primaryColor: '#02235e', secondaryColor: '#FFB81C',jersey: '#FFFFFF', accent: '#ADAFAA', alt: '#FFFFFF', id: 7 },
    MTL: { name: 'Montréal Canadiens', primaryColor: '#001E62', secondaryColor: '#6CACE4', jersey: '#A6192E', accent: '#FFFFFF', alt: '#FFFFFF', id: 8 },
    OTT: { name: 'Ottawa Senators', primaryColor: '#000000', secondaryColor: '#a20620', jersey: '#B9975B', accent: '#FFFFFF', alt: '#B9975B', id: 9 },
    TOR: { name: 'Toronto Maple Leafs', primaryColor: '#00205B', secondaryColor: '#FFFFFF', jersey: '#FFFFFF', accent: '#A2AAAD', alt: '#FFFFFF', id: 10 },
    CAR: { name: 'Carolina Hurricanes', primaryColor: '#000000', secondaryColor: '#b10018', jersey: '#A4A9AD', accent: 'FFFFFF', alt: '#FFFFFF', id: 12 },
    FLA: { name: 'Florida Panthers', primaryColor: '#041E42', secondaryColor: '#b9975B', jersey: '#c8102e', accent: '#FFFFFF', alt: '#', id: 13 },
    TBL: { name: 'Tampa Bay Lightning', primaryColor: '#00205B', secondaryColor: '#FFFFFF', jersey: '#A2AAAD', accent: '#000000', alt: '#', id: 14 },
    WSH: { name: 'Washington Capitals', primaryColor: '#041E42', secondaryColor: '#C8102E', jersey: '#FFFFFF', accent: '#A2AAAD', alt: '#', id: 15},
    CHI: { name: 'Chicago Blackhawks', primaryColor: '#a20620', secondaryColor: '#000000', jersey: '#FFFFFF', accent: '#CC8A00', alt: '#FFFFFF', id: 16},
    DET: { name: 'Detroit Red Wings', primaryColor: '#a20620', secondaryColor: '#FFFFFF', jersey: '#FFFFFF', accent: '#DDCBA4', alt: '#', id: 17},
    NSH: { name: 'Nashville Predators', primaryColor: '#041e42', secondaryColor: '#FFb81c', jersey: '#FFFFFF', accent: '#A2AAAD', alt: '#', id: 18 },
    STL: { name: 'St. Louis Blues', primaryColor: '#041E42', secondaryColor: '#FCB514', jersey: '#1749a8', accent: '#FFFFFF', alt: '#', id: 19 },
    CGY: { name: 'Calgary Flames', primaryColor: '#8a0113', secondaryColor: '#FAAF19', jersey: '#FFFFFF', accent: '#000000', alt: '#', id: 20 },
    COL: { name: 'Colorado Avalanche', primaryColor: '#041e42', secondaryColor: '#902647', jersey: '#236192', accent: '#FFFFFF', alt: '#', id: 21 },
    EDM: { name: 'Edmonton Oilers', primaryColor: '#041E42', secondaryColor: '#FC4C02', jersey: '#FFFFFF', accent: '#A2AAAD', alt: '#', id: 22 },
    VAN: { name: 'Vancouver Canucks', primaryColor: '#00205B', secondaryColor: '#00843D', jersey: '#ffffff', accent: '#041C2C', alt: '#', id: 23 },
    ANA: { name: 'Anaheim Ducks', primaryColor: '#010101', secondaryColor: '#B9975B', jersey: '#FC4C02', accent: '#ffffff', alt: '#FFFFFF', id: 24 },
    DAL: { name: 'Dallas Stars', primaryColor: '#000000', secondaryColor: '#44D62C', jersey: '#44d62c', accent: '#FFFFFF', alt: '#', id: 25 },
    LAK: { name: 'Los Angeles Kings', primaryColor: '#000000', secondaryColor: '#A2AAAD', jersey: '#FFFFFF', accent: '#A2AAAD', alt: '#', id: 26 },
    SJS: { name: 'San Jose Sharks', primaryColor: '#006D75', secondaryColor: '#000000', jersey: '#FFFFFF', accent: '#EA7200', alt: '#', id: 28 },
    CBJ: { name: 'Columbus Blue Jackets', primaryColor: '#002654', secondaryColor: '#7DA1C4', jersey: '#ffffff', accent: '#c8102e', alt: '#', id: 29 },
    MIN: { name: 'Minnesota Wild', primaryColor: '#154734', secondaryColor: '#DDCBA4', jersey: '#A6192E', accent: '#FFFFFF', alt: '#', id: 30 },
    WPG: { name: 'Winnipeg Jets', primaryColor: '#041E42', secondaryColor: '#A2AAAD', jersey: '#004C97', accent: '#55565A', alt: '#', id: 52 },
    ARI: { name: 'Arizona Coyotes', primaryColor: '#8C2633', secondaryColor: '#DDCBA4', jersey: '#ffffff', accent: '#A9431E', alt: '#DDCBA4', id: 53 },
    VGK: { name: 'Vegas Golden Knights', primaryColor: '#24292c', secondaryColor: '#B4975A', jersey: '#7d0518', accent: '#000000', alt: '#', id: 54 },
    SEA: { name: 'Seattle Kraken', primaryColor: '#001628', secondaryColor: '#68A2B9', jersey: '#99D9D9', accent: '#E9072B', alt: '#', id: 55 },
  };
  