import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
const auth = vi.hoisted(() => ({ listeners: [] as any[], getSession: vi.fn(async () => ({ data: { session: { access_token: "token", user: { id: "one" } } } })) }));
vi.mock("lib/supabase/client", () => ({ default: { auth: { getSession: auth.getSession, onAuthStateChange: (listener: any) => { auth.listeners.push(listener); return { data: { subscription: { unsubscribe: vi.fn() } } }; } } } }));
import { useDraftProReports } from "./useDraftProReports";
import { scenarioFingerprint } from "lib/draft-pro/scenarios";
const input: any = { roster: [], leagueType: "points", season: "20262027", source: { projection: { id: "p", version: "v1", origin: "server" }, schedule: { season: "20262027", startWeek: 1, endWeek: 1, lineupMode: "daily", rosterSlots: {} } }, scoring: {} };
const report: any = { schemaVersion: 1, reportType: "draft_summary", sourceFingerprint: "f", createdAt: "2026-09-07T00:00:00Z", season: "20262027", roster: { count: 0, players: [] }, totals: { rawVorp: 0, projectedPoints: 0, categories: {} }, strengths: [], weaknesses: [], schedule: { state: "ready", conflicts: [], diagnostics: [] }, analyticalInput: input, provenance: { projectionId: "p", projectionVersion: "v1", projectionOrigin: "server", season: "20262027", scoring: {}, sourceWeights: {}, freshness: { oldestFetchedAt: null, latestFetchedAt: null } } };
afterEach(() => { cleanup(); auth.listeners.length = 0; vi.unstubAllGlobals(); });
describe("useDraftProReports", () => {
  it("uses the API row payload and retains its new summary", async () => { vi.stubGlobal("fetch", vi.fn(async (_url, init) => ({ ok: true, json: async () => ({ data: init?.method ? { id: "r", report_type: "draft_summary", source_fingerprint: "f", created_at: "2026-09-07T00:00:00Z", payload: report } : [] }) }))); const { result } = renderHook(() => useDraftProReports(true, scenarioFingerprint(input))); await act(async () => {}); await act(async () => { await result.current.generate(input, "draft_summary", { snapshot: { settings: {}, picks: [], keepers: [], team: {}, sourceWeights: {} } }); }); expect(result.current.report?.sourceFingerprint).toBe("f"); expect(result.current.saved[0]?.id).toBe("r"); });
  it("clears premium payload when eligibility is revoked", async () => { vi.stubGlobal("fetch", vi.fn(async (_url, init) => ({ ok: true, json: async () => ({ data: init?.method ? { id: "r", report_type: "draft_summary", source_fingerprint: "f", created_at: "2026-09-07T00:00:00Z", payload: report } : [] }) }))); const { result, rerender } = renderHook(({ eligible }) => useDraftProReports(eligible, scenarioFingerprint(input)), { initialProps: { eligible: true } }); await act(async () => {}); await act(async () => { await result.current.generate(input, "draft_summary", { snapshot: {} }); }); expect(result.current.report).not.toBeNull(); rerender({ eligible: false }); expect(result.current.report).toBeNull(); });
  it("loads retained names while initially inactive", async () => { vi.stubGlobal("fetch", vi.fn(async () => ({ ok: true, json: async () => ({ data: [{ id: "r", report_type: "draft_summary", source_fingerprint: "f", created_at: "2026-09-07T00:00:00Z" }] }) }))); const { result } = renderHook(() => useDraftProReports(false, null)); await act(async () => {}); expect(result.current.saved[0]?.id).toBe("r"); });
  it("retries the exact failed open", async () => { let opens = 0; vi.stubGlobal("fetch", vi.fn(async (url) => { if (String(url).includes("/reports/r")) { opens += 1; return opens === 1 ? { ok: false, json: async () => ({ error: { message: "Open failed" } }) } : { ok: true, json: async () => ({ data: { payload: report } }) }; } return { ok: true, json: async () => ({ data: [] }) }; })); const { result } = renderHook(() => useDraftProReports(true, scenarioFingerprint(input))); await act(async () => {}); await act(async () => { await result.current.open("r"); }); expect(result.current.error).toBe("Open failed"); await act(async () => { await result.current.retry(); }); expect(opens).toBe(2); expect(result.current.report?.sourceFingerprint).toBe("f"); });
  it("rejects a late response after the report context changes", async () => { let resolveAction!: (value: any) => void; vi.stubGlobal("fetch", vi.fn((url, init) => init?.method ? new Promise((resolve) => { resolveAction = resolve; }) : Promise.resolve({ ok: true, json: async () => ({ data: [] }) }))); const { result, rerender } = renderHook(({ context }) => useDraftProReports(true, context), { initialProps: { context: scenarioFingerprint(input) } }); await act(async () => {}); act(() => { void result.current.generate(input, "draft_summary", { snapshot: {} }); }); await act(async () => {}); rerender({ context: "changed" }); resolveAction({ ok: true, json: async () => ({ data: { id: "r", report_type: "draft_summary", source_fingerprint: "f", created_at: "2026-09-07", payload: report } }) }); await act(async () => {}); expect(result.current.report).toBeNull(); expect(result.current.status).toBe("idle"); });
});
