import { describe, expect, it } from "vitest";

import type { TeamStatsTableFamily } from "lib/underlying-stats/teamStatsFilters";

import {
  getAllTeamStatsTableFamilies,
  getTeamStatsColumnByKey,
  getTeamStatsColumns,
  getTeamStatsDefaultSortForFamily,
  getTeamStatsIdentityColumns,
  TEAM_STATS_COUNT_IDENTITY_COLUMN_KEYS,
  TEAM_STATS_IDENTITY_COLUMNS,
  TEAM_STATS_RATE_IDENTITY_COLUMN_KEYS,
} from "./teamStatsColumns";

const EXPECTED_FAMILY_COLUMN_KEYS: Record<TeamStatsTableFamily, string[]> = {
  counts: [
    "teamLabel",
    "gamesPlayed",
    "toiSeconds",
    "wins",
    "losses",
    "otl",
    "rowWins",
    "points",
    "pointPct",
    "cf",
    "ca",
    "cfPct",
    "ff",
    "fa",
    "ffPct",
    "sf",
    "sa",
    "sfPct",
    "gf",
    "ga",
    "gfPct",
    "xgf",
    "xga",
    "xgfPct",
    "scf",
    "sca",
    "scfPct",
    "scsf",
    "scsa",
    "scsfPct",
    "scgf",
    "scga",
    "scgfPct",
    "scshPct",
    "scsvPct",
    "hdcf",
    "hdca",
    "hdcfPct",
    "hdsf",
    "hdsa",
    "hdsfPct",
    "hdgf",
    "hdga",
    "hdgfPct",
    "hdshPct",
    "hdsvPct",
    "mdcf",
    "mdca",
    "mdcfPct",
    "mdsf",
    "mdsa",
    "mdsfPct",
    "mdgf",
    "mdga",
    "mdgfPct",
    "mdshPct",
    "mdsvPct",
    "ldcf",
    "ldca",
    "ldcfPct",
    "ldsf",
    "ldsa",
    "ldsfPct",
    "ldgf",
    "ldga",
    "ldgfPct",
    "ldshPct",
    "ldsvPct",
    "shPct",
    "svPct",
    "pdo",
  ],
  rates: [
    "teamLabel",
    "gamesPlayed",
    "toiPerGameSeconds",
    "wins",
    "losses",
    "otl",
    "rowWins",
    "points",
    "pointPct",
    "cfPer60",
    "caPer60",
    "cfPct",
    "ffPer60",
    "faPer60",
    "ffPct",
    "sfPer60",
    "saPer60",
    "sfPct",
    "gfPer60",
    "gaPer60",
    "gfPct",
    "xgfPer60",
    "xgaPer60",
    "xgfPct",
    "scfPer60",
    "scaPer60",
    "scfPct",
    "scsfPer60",
    "scsaPer60",
    "scsfPct",
    "scgfPer60",
    "scgaPer60",
    "scgfPct",
    "scshPct",
    "scsvPct",
    "hdcfPer60",
    "hdcaPer60",
    "hdcfPct",
    "hdsfPer60",
    "hdsaPer60",
    "hdsfPct",
    "hdgfPer60",
    "hdgaPer60",
    "hdgfPct",
    "hdshPct",
    "hdsvPct",
    "mdcfPer60",
    "mdcaPer60",
    "mdcfPct",
    "mdsfPer60",
    "mdsaPer60",
    "mdsfPct",
    "mdgfPer60",
    "mdgaPer60",
    "mdgfPct",
    "mdshPct",
    "mdsvPct",
    "ldcfPer60",
    "ldcaPer60",
    "ldcfPct",
    "ldsfPer60",
    "ldsaPer60",
    "ldsfPct",
    "ldgfPer60",
    "ldgaPer60",
    "ldgfPct",
    "ldshPct",
    "ldsvPct",
    "shPct",
    "svPct",
    "pdo",
  ],
};

const EXPECTED_FAMILY_COLUMN_LABELS: Record<TeamStatsTableFamily, string[]> = {
  counts: [
    "Team",
    "GP",
    "TOI",
    "W",
    "L",
    "OTL",
    "ROW",
    "Points",
    "Point %",
    "CF",
    "CA",
    "CF%",
    "FF",
    "FA",
    "FF%",
    "SF",
    "SA",
    "SF%",
    "GF",
    "GA",
    "GF%",
    "xGF",
    "xGA",
    "xGF%",
    "SCF",
    "SCA",
    "SCF%",
    "SCSF",
    "SCSA",
    "SCSF%",
    "SCGF",
    "SCGA",
    "SCGF%",
    "SCSH%",
    "SCSV%",
    "HDCF",
    "HDCA",
    "HDCF%",
    "HDSF",
    "HDSA",
    "HDSF%",
    "HDGF",
    "HDGA",
    "HDGF%",
    "HDSH%",
    "HDSV%",
    "MDCF",
    "MDCA",
    "MDCF%",
    "MDSF",
    "MDSA",
    "MDSF%",
    "MDGF",
    "MDGA",
    "MDGF%",
    "MDSH%",
    "MDSV%",
    "LDCF",
    "LDCA",
    "LDCF%",
    "LDSF",
    "LDSA",
    "LDSF%",
    "LDGF",
    "LDGA",
    "LDGF%",
    "LDSH%",
    "LDSV%",
    "SH%",
    "SV%",
    "PDO",
  ],
  rates: [
    "Team",
    "GP",
    "TOI/GP",
    "W",
    "L",
    "OTL",
    "ROW",
    "Points",
    "Point %",
    "CF/60",
    "CA/60",
    "CF%",
    "FF/60",
    "FA/60",
    "FF%",
    "SF/60",
    "SA/60",
    "SF%",
    "GF/60",
    "GA/60",
    "GF%",
    "xGF/60",
    "xGA/60",
    "xGF%",
    "SCF/60",
    "SCA/60",
    "SCF%",
    "SCSF/60",
    "SCSA/60",
    "SCSF%",
    "SCGF/60",
    "SCGA/60",
    "SCGF%",
    "SCSH%",
    "SCSV%",
    "HDCF/60",
    "HDCA/60",
    "HDCF%",
    "HDSF/60",
    "HDSA/60",
    "HDSF%",
    "HDGF/60",
    "HDGA/60",
    "HDGF%",
    "HDSH%",
    "HDSV%",
    "MDCF/60",
    "MDCA/60",
    "MDCF%",
    "MDSF/60",
    "MDSA/60",
    "MDSF%",
    "MDGF/60",
    "MDGA/60",
    "MDGF%",
    "MDSH%",
    "MDSV%",
    "LDCF/60",
    "LDCA/60",
    "LDCF%",
    "LDSF/60",
    "LDSA/60",
    "LDSF%",
    "LDGF/60",
    "LDGA/60",
    "LDGF%",
    "LDSH%",
    "LDSV%",
    "SH%",
    "SV%",
    "PDO",
  ],
};

describe("teamStatsColumns", () => {
  it("returns both supported team table families", () => {
    expect(getAllTeamStatsTableFamilies()).toEqual(["counts", "rates"]);
  });

  it("matches the PRD key order for each family", () => {
    for (const family of getAllTeamStatsTableFamilies()) {
      expect(getTeamStatsColumns(family).map((column) => column.key)).toEqual(
        EXPECTED_FAMILY_COLUMN_KEYS[family]
      );
      expect(getTeamStatsColumns(family).map((column) => column.sortKey)).toEqual(
        EXPECTED_FAMILY_COLUMN_KEYS[family]
      );
    }
  });

  it("matches the PRD labels for each family", () => {
    for (const family of getAllTeamStatsTableFamilies()) {
      expect(getTeamStatsColumns(family).map((column) => column.label)).toEqual(
        EXPECTED_FAMILY_COLUMN_LABELS[family]
      );
    }
  });

  it("keeps the expected sticky identity columns per family", () => {
    expect(TEAM_STATS_COUNT_IDENTITY_COLUMN_KEYS).toEqual(["team", "gp", "toi"]);
    expect(TEAM_STATS_RATE_IDENTITY_COLUMN_KEYS).toEqual([
      "team",
      "gp",
      "toiPerGame",
    ]);
    expect(getTeamStatsIdentityColumns("counts")).toEqual([
      TEAM_STATS_IDENTITY_COLUMNS.team,
      TEAM_STATS_IDENTITY_COLUMNS.gp,
      TEAM_STATS_IDENTITY_COLUMNS.toi,
    ]);
    expect(getTeamStatsIdentityColumns("rates")).toEqual([
      TEAM_STATS_IDENTITY_COLUMNS.team,
      TEAM_STATS_IDENTITY_COLUMNS.gp,
      TEAM_STATS_IDENTITY_COLUMNS.toiPerGame,
    ]);
  });

  it("keeps the default sorts aligned with the locked v1 assumptions", () => {
    expect(getTeamStatsDefaultSortForFamily("counts")).toEqual({
      sortKey: "points",
      direction: "desc",
    });
    expect(getTeamStatsDefaultSortForFamily("rates")).toEqual({
      sortKey: "xgfPct",
      direction: "desc",
    });
  });

  it("assigns the expected formatting for representative team metrics", () => {
    expect(getTeamStatsColumnByKey("counts", "teamLabel")).toMatchObject({
      label: "Team",
      format: "team",
      align: "left",
      isIdentity: true,
    });
    expect(getTeamStatsColumnByKey("counts", "pointPct")).toMatchObject({
      label: "Point %",
      format: "percentage",
      sortKey: "pointPct",
    });
    expect(getTeamStatsColumnByKey("counts", "xgf")).toMatchObject({
      label: "xGF",
      format: "decimal",
      sortKey: "xgf",
    });
    expect(getTeamStatsColumnByKey("rates", "toiPerGameSeconds")).toMatchObject({
      label: "TOI/GP",
      format: "toiPerGame",
      isIdentity: true,
    });
    expect(getTeamStatsColumnByKey("rates", "cfPer60")).toMatchObject({
      label: "CF/60",
      format: "per60",
      sortKey: "cfPer60",
    });
    expect(getTeamStatsColumnByKey("rates", "pdo")).toMatchObject({
      label: "PDO",
      format: "decimal",
      sortKey: "pdo",
    });
  });
});