export const SKATER_LABELS: Record<string, string> = {
  GOALS: "G",
  ASSISTS: "A",
  DEFENSE_POINTS: "DPTS",
  PP_POINTS: "PPP",
  SHOTS_ON_GOAL: "SOG",
  HITS: "HIT",
  BLOCKED_SHOTS: "BLK",
  FACEOFFS_LOST: "FOL",
  FACEOFFS_WON: "FOW",
  GAMES_PLAYED: "GP",
  PENALTY_MINUTES: "PIM",
  POINTS: "PTS",
  PP_ASSISTS: "PPA",
  PP_GOALS: "PPG",
  SH_POINTS: "SHP",
  SH_ASSISTS: "SHA",
  SH_GOALS: "SHG",
  PLUS_MINUS: "+/-",
  TIME_ON_ICE: "TOI",
  TIME_ON_ICE_PER_GAME: "ATOI"
};

