import assert from "node:assert/strict";
import { mkdirSync } from "node:fs";
import { chromium, type Page } from "playwright";
import { installDraftProFreeFixtures } from "../../e2e/draft-pro-fixtures";

const base = process.env.NEXT_URL!; const owner = process.env.USER_A!; const gateway = process.env.SUPABASE_GATEWAY!; const service = process.env.SERVICE_KEY!;
const ownerId = "00000000-0000-4000-8000-000000000041"; const artifacts = process.env.DRAFT_PRO_SCENARIOS_BROWSER_ARTIFACTS ?? "/tmp/draft-pro-scenarios-browser-artifacts";
mkdirSync(artifacts, { recursive: true });
const snapshot = { v: 2, configured: true, currentPick: 1, isSnakeDraft: true, myTeamId: "Team 1", draftSettings: { teamCount: 2, draftOrder: ["Team 1", "Team 2"], draftOrderMode: "standard", rosterConfig: { C: 1, LW: 0, RW: 0, D: 0, G: 0, utility: 0, bench: 0 }, scoringCategories: { GOALS: 3, ASSISTS: 2, SHOTS_ON_GOAL: 0.2 } }, draftedPlayers: [], keepers: [], pickOwnerOverrides: {}, pickTrades: [], positionOverrides: {}, customTeamNames: {} };
const privateSnapshot = {
  ...snapshot,
  sourceControls: { custom_csv_1: { isSelected: true, weight: 1 } },
  goalieSourceControls: {},
  customCsvList: [{
    id: "custom_csv_1", label: "Scenario private rows",
    headers: [
      { original: "Player_Name", standardized: "name", selected: true },
      { original: "Goals", standardized: "GOALS", selected: true },
      { original: "Assists", standardized: "ASSISTS", selected: true },
      { original: "Shots_on_Goal", standardized: "SHOTS_ON_GOAL", selected: true },
    ],
    rows: [
      { player_id: 1001, Player_Name: "Fixture Center", Team_Abbreviation: "AAA", Position: "C", Games_Played: 82, Goals: 34, Assists: 45, Shots_on_Goal: 220 },
      { player_id: 1002, Player_Name: "Fixture Center Two", Team_Abbreviation: "CCC", Position: "C", Games_Played: 82, Goals: 29, Assists: 40, Shots_on_Goal: 200 },
      { player_id: 1003, Player_Name: "Fixture Center Three", Team_Abbreviation: "DDD", Position: "C", Games_Played: 82, Goals: 25, Assists: 35, Shots_on_Goal: 180 },
    ],
  }],
};
const auth = { access_token: owner, refresh_token: owner, token_type: "bearer", expires_in: 3600, expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: ownerId, aud: "authenticated", role: "authenticated", email: "route-a@example.invalid" } };
async function prepare(page: Page, state: unknown = snapshot) { await installDraftProFreeFixtures(page, { seedSnapshot: false }); await page.unroute("**/api/v1/account/draft-pro"); await page.addInitScript(({ state, auth }) => { localStorage.setItem("sb-127-auth-token", JSON.stringify(auth)); sessionStorage.setItem("draft.snapshot.v2", JSON.stringify(state)); }, { state, auth }); page.on("dialog", (dialog) => dialog.accept()); await page.goto(`${base}/draft-dashboard`); if (await page.getByRole("dialog").isVisible().catch(() => false)) await page.keyboard.press("Escape"); }
const workspace = (page: Page) => page.getByRole("region", { name: "A versus B scenario workspace", exact: true });
const isAction = (response: import("playwright").Response, action: string) => response.request().method() === "POST" && new URL(response.url()).pathname === "/api/v1/account/draft-pro/scenarios" && JSON.parse(response.request().postData() || "{}").action === action;
async function setActive(active: boolean) { const response = await fetch(`${gateway}/rest/v1/user_entitlements?user_id=eq.${ownerId}&entitlement_key=eq.draft_pro`, { method: "PATCH", headers: { Authorization: `Bearer ${service}`, apikey: service, "Content-Type": "application/json", Prefer: "return=minimal" }, body: JSON.stringify({ entitlement_status: active ? "active" : "inactive" }) }); assert.equal(response.status, 204); }
async function select(page: Page, names: string[]) { for (const name of names) await page.getByRole("checkbox", { name: `Select ${name} for comparison`, exact: true }).check(); const open = page.getByRole("button", { name: "Open roster impact scenarios", exact: true }); await page.waitForFunction(() => document.querySelector<HTMLButtonElement>('button[aria-label="Open roster impact scenarios"]')?.title === "Compare the selected players against your current roster"); await expectEnabled(open); await open.click(); }
async function expectEnabled(locator: import("playwright").Locator) { assert.equal(await locator.isEnabled(), true, "Roster impact remains blocked after selecting two table players."); }
const browserSnapshot = (page: Page) => page.evaluate(() => JSON.parse(sessionStorage.getItem("draft.snapshot.v2") || "{}"));
async function main() { const browser = await chromium.launch({ headless: true }); try {
  const desktop = await browser.newContext({ viewport: { width: 1280, height: 900 } }); const page = await desktop.newPage(); page.setDefaultTimeout(20_000); page.on("response", (response) => { if (new URL(response.url()).pathname === "/api/v1/account/draft-pro/scenarios") console.error(`scenario-response=${response.status()}; request=${response.request().postData()}`); }); await prepare(page); await select(page, ["Fixture Center", "Fixture Center Two"]);
  const picksBeforeAnalyze = (await browserSnapshot(page)).draftedPlayers; const panel = workspace(page); const analyzeButton = panel.getByRole("button", { name: "Compare A vs B", exact: true }); if (!await analyzeButton.isEnabled()) throw new Error(`Scenario analyze is disabled: panel=${JSON.stringify((await panel.innerText()).slice(0, 3000))}; statuses=${JSON.stringify(await page.getByRole("status").allTextContents())}`); const analyzed = page.waitForResponse((r) => isAction(r, "analyze")); await analyzeButton.click(); const analyzeResponse = await analyzed; assert.equal(analyzeResponse.status(), 200, `Scenario analyze request rejected: ${analyzeResponse.status()} ${await analyzeResponse.text()}`); await panel.getByText("Baseline raw VORP:", { exact: false }).waitFor(); assert.deepEqual((await browserSnapshot(page)).draftedPlayers, picksBeforeAnalyze, "Scenario analysis changed live draft picks.");
  await panel.locator("#scenario-name").fill("Browser scenario"); const saved = page.waitForResponse((r) => isAction(r, "save") && r.status() === 201); await panel.getByRole("button", { name: "Save scenario", exact: true }).click(); await saved; await panel.getByRole("button", { name: "Browser scenario", exact: true }).waitFor();
  await page.screenshot({ path: `${artifacts}/desktop.png`, fullPage: true });
  await page.route("**/api/v1/account/draft-pro/scenarios", (route) => route.abort("failed"), { times: 1 }); await panel.getByRole("button", { name: "Compare A vs B", exact: true }).click(); await panel.getByRole("button", { name: "Retry failed action", exact: true }).waitFor(); const retried = page.waitForResponse((r) => isAction(r, "analyze") && r.status() === 200); await panel.getByRole("button", { name: "Retry failed action", exact: true }).click(); await retried;
  const removeSecond = page.getByRole("checkbox", { name: "Select Fixture Center Two for comparison", exact: true }); await removeSecond.focus(); await page.keyboard.press("Space"); const addThird = page.getByRole("checkbox", { name: "Select Fixture Center Three for comparison", exact: true }); await addThird.focus(); await page.keyboard.press("Space"); const reopen = page.getByRole("button", { name: "Open roster impact scenarios", exact: true }); await reopen.focus(); await page.keyboard.press("Enter"); await panel.getByText("Saved scenario is stale", { exact: false }).waitFor();
  await page.reload(); await page.getByRole("button", { name: "Roster Impact Scenarios", exact: true }).click(); await workspace(page).getByRole("button", { name: "Browser scenario", exact: true }).click(); await workspace(page).getByText("no matching current comparison context", { exact: false }).waitFor();
  const listRetry = await browser.newContext(); const listRetryPage = await listRetry.newPage(); listRetryPage.setDefaultTimeout(20_000); await prepare(listRetryPage); await listRetryPage.route("**/api/v1/account/draft-pro/scenarios", (route) => route.abort("failed"), { times: 1 }); await listRetryPage.getByRole("button", { name: "Roster Impact Scenarios", exact: true }).click(); const listPanel = workspace(listRetryPage); await listPanel.getByRole("button", { name: "Retry saved list", exact: true }).waitFor(); const listRecovered = listRetryPage.waitForResponse((response) => response.request().method() === "GET" && new URL(response.url()).pathname === "/api/v1/account/draft-pro/scenarios" && response.status() === 200); await listPanel.getByRole("button", { name: "Retry saved list", exact: true }).click(); await listRecovered; await listPanel.getByRole("button", { name: "Browser scenario", exact: true }).waitFor(); await listRetry.close();
  const privateContext = await browser.newContext(); const privatePage = await privateContext.newPage(); privatePage.setDefaultTimeout(30_000); let privateUploadRequests = 0; privatePage.on("request", (request) => { if (new URL(request.url()).pathname.includes("/private-imports")) privateUploadRequests += 1; }); await prepare(privatePage, privateSnapshot); await select(privatePage, ["Fixture Center", "Fixture Center Two"]); await privatePage.getByText("Save the selected private projection imports to the current account draft", { exact: false }).waitFor(); assert.equal(privateUploadRequests, 0, "Opening an unsaved private scenario uploaded import data."); await privatePage.getByRole("button", { name: "Saved Drafts", exact: true }).click(); const savedDrafts = privatePage.getByRole("region", { name: "Saved Drafts", exact: true }); await savedDrafts.locator("#new-saved-draft-name").fill("Scenario private draft"); const privateDraftCreated = privatePage.waitForResponse((response) => response.request().method() === "POST" && new URL(response.url()).pathname === "/api/v1/account/draft-pro/drafts" && response.status() === 201); await savedDrafts.getByRole("button", { name: "Save to account", exact: true }).click(); await privateDraftCreated; await savedDrafts.getByRole("status").filter({ hasText: "Saved to account." }).waitFor(); const privatePanel = workspace(privatePage); await privatePage.getByText("Save the selected private projection imports to the current account draft", { exact: false }).waitFor({ state: "hidden" }); const privateAnalyze = privatePage.waitForResponse((response) => isAction(response, "analyze")); await privatePanel.getByRole("button", { name: "Compare A vs B", exact: true }).click(); const privateAnalyzeResponse = await privateAnalyze; assert.equal(privateAnalyzeResponse.status(), 200, `Saved-private scenario analyze rejected: ${privateAnalyzeResponse.status()} ${await privateAnalyzeResponse.text()}`); const privateAnalyzeBody = JSON.parse(privateAnalyzeResponse.request().postData() || "{}"); assert.match(privateAnalyzeBody.draftId, /^[0-9a-f-]{36}$/i); assert.equal(privateAnalyzeBody.scenario.source.projection.origin, "saved_private_import"); assert.equal(privateAnalyzeBody.scenario.source.projection.privateImports.length, 1); assert.deepEqual((await browserSnapshot(privatePage)).draftedPlayers, privateSnapshot.draftedPlayers, "Saved-private analysis changed live draft picks.");
  await privatePage.getByRole("button", { name: "Setup", exact: true }).click(); const importCsv = privatePage.getByRole("button", { name: "Import CSV", exact: true }); await importCsv.focus(); await privatePage.keyboard.press("Enter"); const importDialog = privatePage.getByRole("dialog", { name: "Import Projections (CSV)", exact: true }); await importDialog.getByLabel("CSV File Input").setInputFiles({
    name: "scenario-changed.csv", mimeType: "text/csv",
    buffer: Buffer.from("Player Name,team,pos,gp,g,a,pts,ppp,sog,hits,blocks\nFixture Center,AAA,C,82,35,45,80,20,225,20,20\nFixture Center Two,CCC,C,82,30,40,70,15,205,18,18\nFixture Center Three,DDD,C,82,26,35,61,10,185,16,16\n"),
  }); await importDialog.locator("#sourceName").fill("Scenario changed rows"); const confirmImport = importDialog.getByRole("button", { name: "Confirm Import", exact: true }); await confirmImport.waitFor(); await privatePage.waitForFunction(() => !(document.querySelector('button') ? [...document.querySelectorAll('button')].find((button) => button.textContent?.trim() === "Confirm Import")?.hasAttribute("disabled") : true)); await confirmImport.click(); await importDialog.waitFor({ state: "hidden" }); await privatePage.getByText("Scenario changed rows has changed or is not saved", { exact: false }).waitFor(); const uploadsAfterExplicitSave = privateUploadRequests; await privatePage.getByRole("button", { name: "Hide Roster Impact", exact: true }).click(); await privatePage.getByRole("button", { name: "Roster Impact Scenarios", exact: true }).click(); await privatePage.getByText("Scenario changed rows has changed or is not saved", { exact: false }).waitFor(); assert.equal(privateUploadRequests, uploadsAfterExplicitSave, "Reopening a changed private scenario implicitly uploaded local rows."); await privatePage.screenshot({ path: `${artifacts}/desktop-private.png`, fullPage: true }); await privateContext.close();
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 } }); const mobilePage = await mobile.newPage(); mobilePage.setDefaultTimeout(20_000); await prepare(mobilePage); await mobilePage.getByRole("button", { name: "Roster Impact Scenarios", exact: true }).focus(); await mobilePage.keyboard.press("Enter"); const mobilePanel = workspace(mobilePage); await mobilePanel.getByRole("button", { name: "Browser scenario", exact: true }).click(); await mobilePanel.getByText("Fixture Center", { exact: true }).waitFor(); await mobilePanel.getByText("Fixture Center Two", { exact: true }).waitFor(); assert.equal(await mobilePage.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth), true, "Loaded mobile scenario overflows the viewport horizontally."); await mobilePage.screenshot({ path: `${artifacts}/mobile.png`, fullPage: true }); await mobile.close();
  await setActive(false); const inactive = await browser.newContext(); const inactivePage = await inactive.newPage(); inactivePage.setDefaultTimeout(20_000); await prepare(inactivePage); await inactivePage.getByRole("button", { name: "Roster Impact Scenarios", exact: true }).click(); const locked = workspace(inactivePage); await locked.getByText("Existing free two-player comparison remains available", { exact: false }).waitFor(); await locked.getByRole("button", { name: "Browser scenario", exact: true }).waitFor(); assert.equal(await locked.getByRole("button", { name: "Browser scenario", exact: true }).isDisabled(), true); await inactive.close(); await setActive(true); await desktop.close(); console.log("scenarios_browser=passed; analyze-save-open=real; picks=unchanged; stale=real; action-retry=real; list-retry=real; private=unsaved-and-changed-no-upload-plus-saved-owned-analyze; inactive=names-locked; screenshots=desktop-private-mobile");
} finally { await browser.close(); } }
main().catch((error) => { console.error(error); process.exit(1); });
