create table public.roster_optimizer_team_games (
  id bigint generated by default as identity primary key,
  yahoo_matchup_week_id integer,
  game_key text not null,
  season text not null,
  week integer,
  source_game_id bigint not null,
  source_season_id bigint not null,
  game_date date not null,
  start_time timestamptz,
  game_type smallint not null,
  game_status text not null,
  schedule_status text not null,
  mapping_status text not null,
  is_countable boolean not null default false,
  team_id smallint not null,
  team_abbreviation character(3) not null,
  opponent_team_id smallint not null,
  opponent_abbreviation character(3) not null,
  home_away text not null,
  source_url text not null,
  source_updated_at timestamptz,
  source_metadata jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null,
  inserted_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  constraint roster_optimizer_team_games_matchup_week_fkey
    foreign key (yahoo_matchup_week_id)
    references public.yahoo_matchup_weeks (id)
    on update restrict
    on delete restrict,
  constraint roster_optimizer_team_games_team_fkey
    foreign key (team_id)
    references public.teams (id)
    on update restrict
    on delete restrict,
  constraint roster_optimizer_team_games_opponent_team_fkey
    foreign key (opponent_team_id)
    references public.teams (id)
    on update restrict
    on delete restrict,
  constraint roster_optimizer_team_games_home_away_check
    check (home_away in ('home', 'away')),
  constraint roster_optimizer_team_games_mapping_status_check
    check (
      (mapping_status = 'mapped' and yahoo_matchup_week_id is not null and week is not null)
      or
      (mapping_status = 'unmapped' and yahoo_matchup_week_id is null and week is null and is_countable = false)
    ),
  constraint roster_optimizer_team_games_identity_key
    unique (game_key, source_game_id, team_id)
);

comment on table public.roster_optimizer_team_games is
  'Indexed one-row-per-team NHL schedule cache for exact roster Bench Games and DUST calculations.';
comment on column public.roster_optimizer_team_games.game_date is
  'Canonical NHL gameDate scoring date; it is intentionally not derived from the UTC start timestamp.';
comment on column public.roster_optimizer_team_games.is_countable is
  'True only for mapped regular-season games whose NHL game and schedule states are countable.';
comment on column public.roster_optimizer_team_games.source_metadata is
  'Diagnostic NHL source and synchronization metadata; not an authorization surface.';

create index roster_optimizer_team_games_context_week_idx
  on public.roster_optimizer_team_games (game_key, week, game_date);
create index roster_optimizer_team_games_context_team_date_idx
  on public.roster_optimizer_team_games (game_key, team_id, game_date);
create index roster_optimizer_team_games_season_team_idx
  on public.roster_optimizer_team_games (season, team_id);
create index roster_optimizer_team_games_game_date_idx
  on public.roster_optimizer_team_games (game_date);
create index roster_optimizer_team_games_matchup_week_idx
  on public.roster_optimizer_team_games (yahoo_matchup_week_id);

create trigger roster_optimizer_team_games_set_updated_at
before update on public.roster_optimizer_team_games
for each row execute function public.touch_updated_at();

alter table public.roster_optimizer_team_games enable row level security;
alter table public.roster_optimizer_team_games force row level security;

revoke all on table public.roster_optimizer_team_games
  from public, anon, authenticated, service_role;
revoke all on sequence public.roster_optimizer_team_games_id_seq
  from public, anon, authenticated, service_role;

grant select on table public.roster_optimizer_team_games
  to anon, authenticated;
grant select, insert, update, delete on table public.roster_optimizer_team_games
  to service_role;
grant usage, select on sequence public.roster_optimizer_team_games_id_seq
  to service_role;

create policy roster_optimizer_team_games_public_read
on public.roster_optimizer_team_games
for select
to anon, authenticated
using (true);
