-- Make the active TypeScript sustainability pipeline's model/config identity
-- first-class without rewriting legacy score or prior history.

alter table public.model_sustainability_config
  add column if not exists score_model_version text,
  add column if not exists config_hash text;

update public.model_sustainability_config
set score_model_version = coalesce(
      nullif(btrim(score_model_version), ''),
      'legacy_draft_v1'
    ),
    config_hash = coalesce(
      nullif(btrim(config_hash), ''),
      'legacy_unversioned'
    )
where score_model_version is null
   or config_hash is null
   or btrim(score_model_version) = ''
   or btrim(config_hash) = '';

alter table public.model_sustainability_config
  alter column score_model_version set not null,
  alter column config_hash set not null;

alter table public.model_sustainability_config
  drop constraint if exists model_sustainability_config_score_model_nonblank,
  add constraint model_sustainability_config_score_model_nonblank
    check (
      nullif(btrim(score_model_version), '') is not null
      and char_length(score_model_version) <= 80
    ),
  drop constraint if exists model_sustainability_config_hash_nonblank,
  add constraint model_sustainability_config_hash_nonblank
    check (
      nullif(btrim(config_hash), '') is not null
      and char_length(config_hash) <= 128
    );

create unique index if not exists
  model_sustainability_config_one_active_idx
on public.model_sustainability_config ((active))
where active;

revoke insert, update, delete, truncate, references, trigger
  on table public.model_sustainability_config
  from anon, authenticated;
revoke usage, select
  on sequence public.model_sustainability_config_id_seq
  from anon, authenticated;
grant select on table public.model_sustainability_config to anon, authenticated;

alter table public.sustainability_scores
  add column if not exists model_version text,
  add column if not exists config_hash text;

update public.sustainability_scores
set model_version = coalesce(
      nullif(btrim(model_version), ''),
      nullif(btrim(components ->> 'modelVersion'), ''),
      'legacy_unversioned'
    ),
    config_hash = coalesce(
      nullif(btrim(config_hash), ''),
      nullif(btrim(components ->> 'configHash'), ''),
      'legacy_unversioned'
    )
where model_version is null
   or config_hash is null
   or btrim(model_version) = ''
   or btrim(config_hash) = '';

alter table public.sustainability_scores
  alter column model_version set not null,
  alter column config_hash set not null;

alter table public.sustainability_scores
  drop constraint if exists sustainability_scores_model_version_nonblank,
  add constraint sustainability_scores_model_version_nonblank
    check (
      nullif(btrim(model_version), '') is not null
      and char_length(model_version) <= 80
    ),
  drop constraint if exists sustainability_scores_config_hash_nonblank,
  add constraint sustainability_scores_config_hash_nonblank
    check (
      nullif(btrim(config_hash), '') is not null
      and char_length(config_hash) <= 128
    );

create index if not exists sustainability_scores_version_hash_idx
  on public.sustainability_scores (model_version, config_hash, snapshot_date desc);

alter table public.sustainability_player_priors
  add column if not exists model_version text,
  add column if not exists config_hash text;

update public.sustainability_player_priors
set model_version = coalesce(
      nullif(btrim(model_version), ''),
      'legacy_unversioned'
    ),
    config_hash = coalesce(
      nullif(btrim(config_hash), ''),
      'legacy_unversioned'
    )
where model_version is null
   or config_hash is null
   or btrim(model_version) = ''
   or btrim(config_hash) = '';

alter table public.sustainability_player_priors
  alter column model_version set not null,
  alter column config_hash set not null;

alter table public.sustainability_player_priors
  drop constraint if exists sustainability_player_priors_model_version_nonblank,
  add constraint sustainability_player_priors_model_version_nonblank
    check (
      nullif(btrim(model_version), '') is not null
      and char_length(model_version) <= 80
    ),
  drop constraint if exists sustainability_player_priors_config_hash_nonblank,
  add constraint sustainability_player_priors_config_hash_nonblank
    check (
      nullif(btrim(config_hash), '') is not null
      and char_length(config_hash) <= 128
    );

create table if not exists public.sustainability_recompute_queue (
  id bigint generated by default as identity primary key,
  config_revision integer not null,
  model_version text not null,
  config_hash text not null,
  reason text not null,
  status text not null default 'queued',
  attempts integer not null default 0,
  cursor jsonb,
  last_error text,
  enqueued_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  constraint sustainability_recompute_queue_revision_positive
    check (config_revision > 0),
  constraint sustainability_recompute_queue_model_nonblank
    check (
      nullif(btrim(model_version), '') is not null
      and char_length(model_version) <= 80
    ),
  constraint sustainability_recompute_queue_hash_nonblank
    check (
      nullif(btrim(config_hash), '') is not null
      and char_length(config_hash) <= 128
    ),
  constraint sustainability_recompute_queue_reason_check
    check (reason in ('config_change', 'data_backfill')),
  constraint sustainability_recompute_queue_status_check
    check (status in ('queued', 'running', 'completed', 'failed')),
  constraint sustainability_recompute_queue_attempts_nonnegative
    check (attempts >= 0)
);

create unique index if not exists
  sustainability_recompute_queue_active_config_idx
on public.sustainability_recompute_queue
  (config_revision, model_version, config_hash)
where status in ('queued', 'running');

alter table public.sustainability_recompute_queue enable row level security;
alter table public.sustainability_recompute_queue force row level security;
revoke all on table public.sustainability_recompute_queue from public, anon, authenticated;
revoke all on sequence public.sustainability_recompute_queue_id_seq
  from public, anon, authenticated;
grant select, insert, update on table public.sustainability_recompute_queue
  to service_role;
grant usage, select on sequence public.sustainability_recompute_queue_id_seq
  to service_role;

create or replace function public.activate_sustainability_config(
  p_config_revision integer,
  p_model_version text,
  p_config_hash text,
  p_weights jsonb,
  p_toggles jsonb,
  p_constants jsonb,
  p_sd_mode text,
  p_freshness_days integer,
  p_reason text default 'config_change'
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog
as $function$
declare
  v_current_revision integer;
  v_queue_id bigint;
begin
  if p_config_revision is null or p_config_revision <= 0 then
    raise exception 'config revision must be positive';
  end if;
  if nullif(btrim(p_model_version), '') is null
     or char_length(p_model_version) > 80 then
    raise exception 'model version is invalid';
  end if;
  if nullif(btrim(p_config_hash), '') is null
     or char_length(p_config_hash) > 128
     or p_config_hash !~ '^fnv1a_[0-9a-f]{8}$' then
    raise exception 'config hash is invalid';
  end if;
  if jsonb_typeof(p_weights) <> 'object'
     or jsonb_typeof(p_weights -> 'luck') <> 'object'
     or jsonb_typeof(p_weights -> 'skill') <> 'object'
     or not (p_weights -> 'luck' ?& array['shp', 'oishp', 'ipp', 'ppshp'])
     or not (p_weights -> 'skill' ?& array['ixg60', 'icf60', 'hdcf60']) then
    raise exception 'weights must match the canonical score contract';
  end if;
  if jsonb_typeof(p_toggles) <> 'object'
     or jsonb_typeof(p_constants) <> 'object' then
    raise exception 'toggles and constants must be objects';
  end if;
  if p_sd_mode not in ('fixed', 'empirical') then
    raise exception 'sd mode is invalid';
  end if;
  if p_freshness_days is null or p_freshness_days < 1
     or p_freshness_days > 365 then
    raise exception 'freshness days is invalid';
  end if;
  if p_reason not in ('config_change', 'data_backfill') then
    raise exception 'recompute reason is invalid';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('sustainability_config_activation', 0)
  );

  select max(config.model_version)
    into v_current_revision
  from public.model_sustainability_config as config;

  if p_config_revision <> coalesce(v_current_revision, 0) + 1 then
    raise exception 'config revision must advance exactly once';
  end if;

  update public.model_sustainability_config
  set active = false,
      updated_at = now()
  where active;

  insert into public.model_sustainability_config (
    model_version,
    score_model_version,
    config_hash,
    active,
    weights_json,
    toggles_json,
    constants_json,
    sd_mode,
    freshness_days
  )
  values (
    p_config_revision,
    btrim(p_model_version),
    btrim(p_config_hash),
    true,
    p_weights,
    p_toggles,
    p_constants,
    p_sd_mode,
    p_freshness_days
  );

  insert into public.sustainability_recompute_queue (
    config_revision,
    model_version,
    config_hash,
    reason
  )
  values (
    p_config_revision,
    btrim(p_model_version),
    btrim(p_config_hash),
    p_reason
  )
  returning id into v_queue_id;

  return jsonb_build_object(
    'configRevision', p_config_revision,
    'modelVersion', btrim(p_model_version),
    'configHash', btrim(p_config_hash),
    'queueId', v_queue_id,
    'queueStatus', 'queued'
  );
end;
$function$;

revoke all on function public.activate_sustainability_config(
  integer, text, text, jsonb, jsonb, jsonb, text, integer, text
) from public, anon, authenticated;
grant execute on function public.activate_sustainability_config(
  integer, text, text, jsonb, jsonb, jsonb, text, integer, text
) to service_role;

select public.activate_sustainability_config(
  2,
  'sustainability_score_v2',
  'fnv1a_91691726',
  '{
    "luck": {"shp": -1.2, "oishp": -1.0, "ipp": -0.8, "ppshp": -0.4},
    "skill": {"ixg60": 0.9, "icf60": 0.7, "hdcf60": 0.6}
  }'::jsonb,
  '{}'::jsonb,
  '{
    "scorePrecision": 2,
    "exactScoreProbabilityThresholds": {"lower": 0.005, "upper": 0.995},
    "windowCodes": ["l3", "l5", "l10", "l20"]
  }'::jsonb,
  'fixed',
  45,
  'config_change'
);
